<section id="image">
	<div class="container">
		<div class="col-md-8 col-md-offset-2">
			<div class="text-banner">
				<div class="description tc" style="height:230px;">
					<h2 style="color:#fff">LETS CREATE THE BEST! ENJOY WORKING WITH RESERVEDINE</h2>
					<p style="color:#fff">
					   ReserveDine is a location based restaurant locator application. ReserveDine helps power business of restaurants by directing customers to their door steps. The unique algorithm assists guests in locating restaurants based on their liking for food, age, taste, season, choice, location etc. The fun to have app also offers discounts and offers to its guests.
					</p>
				</div>
			</div>
		</div>
	</div>
	<!--/.container-->
	<div class="background">
		<img src="images/careers-banner.jpg" alt="">
	</div>
	<!--/.bakcground-->
</section>
<section class="tabs_wrap">				
	<div class="container">
	  <div class="row">
		<div class="col-xs-12">						  
			  <a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'about'),'about',true); ?>" class="tabs">About Us</a>
			  <a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'careers'),'careers',true); ?>" class="sel tabs">Careers</a>
			  <a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'news'),'news',true); ?>" class="tabs">News & Press</a>
			  <a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'contact'),'contact',true); ?>" class="tabs">Contact</a>							
		</div>
	  </div>
	</div>
</section>
<section class="about">
	<div class="container">
		<div class="row">
			<div class="static_wrap">
				<h1>WORK FOR ReserveDine</h1>
				<h3 class="tc">Are you looking for a new challenge?</h3>
				<p>ReserveDine is a startup filled with enthusiastic, young and eager individuals. We believe in being quick on our feet, harbouring grand visions of our community of food lovers and working with the best and brightest that come our way. At ReserveDine you get the best of working at a startup under the guidance of people who have worked with Fortune 500 Consulting firms. And we are proud of having them in ReserveDine. We believe in introspection and thus urge you to answer a few questions before you read our benefits.</p>
				<ul class="static_list">
					<li>Is food on your mind all the time?</li>
					<li>Do you believe you can use technology to change the way information is shown?</li>
					<li>Does passing out at 3 am sound familiar?</li>
					<li>Do you like to work hard? And party harder?</li>
					<li>Is the idea of challenging the boss at Age of Empires 2/Counter Strike thrilling?</li>
				</ul>
				<div class="clear gap"></div>
				<p>If your answer is YES, then write an email to <a href="mailto:hr@ReserveDine.com" style="font-weight: bold; font-size: 14px; cursor: pointer; color: #000; text-decoration: none;">hr@ReserveDine.com.</a> We will explore opportunity to work with you.</p>
				<div class="clear gap"></div>
			</div>
		</div>
	</div>
</section>
<section id="image">
	<div class="container">
		<div class="col-md-6">
			<div class="text-banner">
				<div class="description">
					<h2 style="color:#fff">LIFE AT ReserveDine</h2>
					<p>
					   The biggest benefit of working at ReserveDine? The insanely talented and passionate people you get to work with on a daily basis. People who believe in action and will stop at nothing to get something done.
					</p>
					<div class="clear gap"></div>
					<div class="clear gap"></div>
					<div class="clear gap"></div>
					<p style="color:#fff">apart from that, why should you work at ReserveDine?</p>
					<ul class="static_list">
						<li>Work on something really really important; something which affects the lives of millions of people</li>
						<li>Genuinely fun work culture (no BS, all straight talk) with cool folks</li>
						<li>We move fast; we don't have any annual plans - we always pack everything within the next three months</li>
						<li>Serious real world training and mentorship while working in a very flat organizational structure</li>
						<li>Push yourself harder than you have ever before</li>
						<li>In our customers' words, save lives!</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!--/.container-->
	<div class="background">
		<img src="images/banner12.jpg" alt="">
	</div>
	<!--/.bakcground-->
</section>
<section class="block" id="features">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="tc">OUR MANTRA</h1>
				<p class="tc">Faster. Smarter. Easier.</p>
			</div>
			<div class="col-md-4 col-sm-4">
				<div class="feature-box">
					<i class="soap-icon-breakfast"></i>
					<div class="description">
						<h3>OUT SEE </h3>
						<p>
							We see the world differently. We aim higher, dream bigger and explore further. We try to make everything better than anything ever done before.
						</p>
					</div>
				</div>
				<!--/.feature-box-->
			</div>
			<!--/.col-md-4-->
			<div class="col-md-4 col-sm-4">
				<div class="feature-box">
					<i class="soap-icon-conference"></i>
					<div class="description">
						<h3>OUT THINK</h3>
						<p>
							We solve problems differently. We combine knowledge, passion and technology to drive innovation and set new benchmarks for excellence.
						</p>
					</div>
				</div>
				<!--/.feature-box-->
			</div>
			<!--/.col-md-4-->
			<div class="col-md-4 col-sm-4">
				<div class="feature-box">
					<i class="soap-icon-flexible"></i>
					<div class="description">
						<h3>OUT DO </h3>
						<p>
							We do things differently. We don't stop at success, we always ask 'what next?' so we can change the game and keep on winning.
						</p>
					</div>
				</div>
				<!--/.feature-box-->
			</div>
			<!--/.col-md-4-->
		</div>
		<!--/.row-->
	</div>
	<!--/.container-->
</section>