
<?php if(isset($this->successmsg)){
	echo '<script>alert("Thank you for contacting us, our executive will contact you shortly.</script>';
	}?>
<section id="image">
	<div class="container">
		<div class="col-md-8 col-md-offset-2">
			<div class="text-banner">
				<div class="description tc" style="height:230px;">
					<h2 style="color:#fff">A global company with global perspective</h2>
					<p>
					   ReserveDine is a location based restaurant locator application. ReserveDine helps power business of restaurants by directing customers to their door steps. The unique algorithm assists guests in locating restaurants based on their liking for food, age, taste, season, choice, location etc. 
					</p>
				</div>
			</div>
		</div>
	</div>
	<!--/.container-->
	<div class="background">
		<img src="images/contact_us.jpg" alt="">
	</div>
	<!--/.bakcground-->
</section>
<section class="tabs_wrap">				
	<div class="container">
	  <div class="row">
		<div class="col-xs-12">						  
			  <a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'about'),'about',true); ?>" class="tabs">About Us</a>
			  <a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'careers'),'careers',true); ?>" class="tabs">Careers</a>
			  <a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'news'),'news',true); ?>" class="tabs">News & Press</a>
			  <a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'contact'),'contact',true); ?>" class="sel tabs">Contact</a>							
		</div>
	  </div>
	</div>
</section>
<section class="about">
	<div class="container">
		<div class="row">
			<div class="static_wrap">
				<h1>Contact ReserveDine 24/7</h1>
				<h3 class="tc">We're available online 24 hours a day. Just click on the chat widget on the bottom right corner of the screen. Don't worry: We're friendly humans, not chat robots.</h3>
				<div class="clear gap"></div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<header class="no-border"><h2>Please complete the contact form below.</h2></header>										
				<form id="contact-form" role="form" method="post" action="<?php echo $this->url(array('controller'=>'index','action'=>'contactus'));  ?>" class="background-color-white" style="padding:0;">
					<div class="row">
						<div class="col-md-12 col-sm-12">
							<div class="form-group">
								<label for="company-form-name">Name</label>
								<?php echo $this->contactform->contactName; ?>
							</div>
							<!-- /.form-group -->
						</div>
						<div class="col-md-6 col-sm-6">
							<div class="form-group">
								<label for="company-form-email">Email</label>
								<?php echo $this->contactform->emailAddress; ?>
							</div>
							<!-- /.form-group -->
						</div>
						<!--/.col-md-6-->
						<div class="col-md-6 col-sm-6">
							<div class="form-group">
								<label for="company-form-email">Phone</label>
								<?php echo $this->contactform->phone; ?>
							</div>
							<!-- /.form-group -->
						</div>
						<!--/.col-md-6-->
					</div>
					<div class="form-group">
						<label for="company-form-message">Message</label>
						<?php echo $this->contactform->comments; ?>
						<?php echo $this->contactform->type; ?>
					</div>
					<div class="form-group">
						<?php echo $this->contactform->captcha->setAttrib('placeholder','Enter characters as shown in box');?>
					</div>
					<!-- /.form-group -->
					<div class="form-group">
						<button type="submit" class="btn btn-default icon">Send a Message<i class="fa fa-angle-right"></i></button>
					</div>
					
					<!-- /.form-group -->
				</form>
					<!--/#contact-form-->
			</div>
			<div class="col-md-6">
				<header class="no-border"><h2>We Look Forward To Hearing From You</h2></header>		
				<p>Our team will review your comments and suggestions and will get back to you shortly.</p>
				<h3><b>You can also reach us by Email</b></h3>
				<div class="clear gap"></div>
				<p>Tell us what you think of ReserveDine!<br> <a href="mailto:feedback@ReserveDine.com">feedback@ReserveDine.com</a></p>
				<div class="clear gap"></div>
				<p>Technical Support &nbsp;&nbsp;&nbsp;&nbsp;  &nbsp;&nbsp;&nbsp;&nbsp;  &nbsp; (OR) &nbsp;&nbsp;&nbsp;&nbsp;  Click here for support<br> <a href="mailto:support@ReserveDine.com">support@ReserveDine.com</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://support.ReserveDine.com/" target="_blank">support.ReserveDine.com</a></p>
				<div class="clear gap"></div>
				<p>Strategic Partnerships<br><a href="mailto:sales@ReserveDine.com">sales@ReserveDine.com</a></p>
			</div>
		</div>	
	</div>
</section>

<section class="block" id="features">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="tc">OUR MANTRA</h1>
				<p class="tc">Faster. Smarter. Easier.</p>
			</div>
			<div class="col-md-4 col-sm-4">
				<div class="feature-box">
					<i class="soap-icon-breakfast"></i>
					<div class="description">
						<h3>OUT SEE </h3>
						<p>
							We see the world differently. We aim higher, dream bigger and explore further. We try to make everything better than anything ever done before.
						</p>
					</div>
				</div>
				<!--/.feature-box-->
			</div>
			<!--/.col-md-4-->
			<div class="col-md-4 col-sm-4">
				<div class="feature-box">
					<i class="soap-icon-conference"></i>
					<div class="description">
						<h3>OUT THINK</h3>
						<p>
							We solve problems differently. We combine knowledge, passion and technology to drive innovation and set new benchmarks for excellence.
						</p>
					</div>
				</div>
				<!--/.feature-box-->
			</div>
			<!--/.col-md-4-->
			<div class="col-md-4 col-sm-4">
				<div class="feature-box">
					<i class="soap-icon-flexible"></i>
					<div class="description">
						<h3>OUT DO </h3>
						<p>
							We do things differently. We don't stop at success, we always ask 'what next?' so we can change the game and keep on winning.
						</p>
					</div>
				</div>
				<!--/.feature-box-->
			</div>
			<!--/.col-md-4-->
		</div>
		<!--/.row-->
	</div>
	<!--/.container-->
</section>
