<section id="image">
	<div class="container">
		<div class="col-md-8 col-md-offset-2">
			<div class="text-banner">
				<div class="description tc" style="height:230px;">
					
				</div>
			</div>
		</div>
	</div>
	<!--/.container-->
	<div class="background">
		<img src="images/banner_news.jpg" alt="">
	</div>
	<!--/.bakcground-->
</section>
<section class="tabs_wrap">				
	<div class="container">
	  <div class="row">
		<div class="col-xs-12">						  
			  <a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'about'),'about',true); ?>" class="tabs">About Us</a>
			  <a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'careers'),'careers',true); ?>" class="tabs">Careers</a>
			  <a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'news'),'news',true); ?>" class="sel tabs">News & Press</a>
			  <a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'contact'),'contact',true); ?>" class="tabs">Contact</a>							
		</div>
	  </div>
	</div>
</section>
<section class="about">
	<div class="container">
		<div class="row">
			<div class="static_wrap">
				<h1>NEWS & PRESS</h1>
				<h3 class="tc">News section will be updated soon!</h3>				
			</div>
		</div>
	</div>
</section>
<section class="block" id="features">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="tc">OUR MANTRA</h1>
				<p class="tc">Faster. Smarter. Easier.</p>
			</div>
			<div class="col-md-4 col-sm-4">
				<div class="feature-box">
					<i class="soap-icon-breakfast"></i>
					<div class="description">
						<h3>OUT SEE </h3>
						<p>
							We see the world differently. We aim higher, dream bigger and explore further. We try to make everything better than anything ever done before.
						</p>
					</div>
				</div>
				<!--/.feature-box-->
			</div>
			<!--/.col-md-4-->
			<div class="col-md-4 col-sm-4">
				<div class="feature-box">
					<i class="soap-icon-conference"></i>
					<div class="description">
						<h3>OUT THINK</h3>
						<p>
							We solve problems differently. We combine knowledge, passion and technology to drive innovation and set new benchmarks for excellence.
						</p>
					</div>
				</div>
				<!--/.feature-box-->
			</div>
			<!--/.col-md-4-->
			<div class="col-md-4 col-sm-4">
				<div class="feature-box">
					<i class="soap-icon-flexible"></i>
					<div class="description">
						<h3>OUT DO </h3>
						<p>
							We do things differently. We don't stop at success, we always ask 'what next?' so we can change the game and keep on winning.
						</p>
					</div>
				</div>
				<!--/.feature-box-->
			</div>
			<!--/.col-md-4-->
		</div>
		<!--/.row-->
	</div>
	<!--/.container-->
</section>