

<section id="image">
	<div class="container">
		<div class="col-md-8 col-md-offset-2">
			<div class="text-banner">
				<div class="description tc" style="height:230px;">
					<h2 style="color:#fff">TERMS AND CONDITIONS</h2>
					
				</div>
			</div>
		</div>
	</div>
	<!--/.container-->
	<div class="background">
		<img src="images/trems-banner.jpg" alt="">
	</div>
	<!--/.bakcground-->
</section>
<section class="tabs_wrap">				
	<div class="container">
	  <div class="row">
		<div class="col-xs-12">						  
			  <a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'faqs'),'faqs',true); ?>" class="tabs">FAQS</a>
			  <a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'privacy'),'privacy',true); ?>" class="tabs">Privacy Policy</a>
			  <a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'terms'),'termsofservice',true); ?>" class="sel tabs">TERMS & CONDITIONS</a>							
		</div>
	  </div>
	</div>
</section>
<section class="about">
	<div class="container">
		<div class="row">
			<div class="block">
				<p>By providing your personal details to us, you signify your acceptance of our Privacy Policy. If you do not agree to this Privacy Policy, please do not provide your personal details to us.</p>
				<p>This Privacy Policy is incorporated into, and part of, the Terms and Conditions which govern your use of the website www.ReserveDine.com (Site) in general.</p>
				<p>We may need to update this Privacy Policy from time to time. We recommend that you regularly check this page to ensure that you have read the most recent version.</p>
				<h2>1 Collecting personal information</h2>
				<p>1.1  You can decide what personal information you provide to us. We will only collect personal information that you choose to provide. Where possible, we will enable you to select how we will use this information (for example, by choosing to opt-in or opt-out of receiving special promotional offers).</p>
				<p>1.2 You may choose to provide us with personal information if, for example, you: contact us with an enquiry, register on the Site, fill out a survey or other form with your personal information included, request us to provide you with information. enter a competition, post information to public areas of the site or participate in a promotion.</p>
				<p>1.3 You have the opportunity to choose not to opt-in receive communications from us at any point where we request information about you.</p>
				<p>1.4 If you want to register as a User on this Site, the only information we will require of you is the following:</p>
				<p>1.4.1 your name and surname;</p>
				<p>1.4.2 your email address;</p>
				<p>1.5 You may choose to provide additional personal information to us, in which event you agree to provide accurate and current information, and not to impersonate or misrepresent any person or entity or falsely state or otherwise misrepresent your affiliation with anyone or anything.</p>
				<p>1.6 Third parties (including but not limited to software providers, advertisers and ad placement agencies) may also use tracking technologies by or through the Site. We have no responsibility or liability for any tracking, data collection or other activities of such third parties.</p>
				<h2>2 Our use of personal information</h2>
				<p>We will use information collected from you in the following ways:</p>
				<p>2.1 <b>Marketing purposes:</b>We may use information for internal marketing analysis, for example, to assess trends amongst our consumers or to measure the amount of traffic to our Site. When you give permission for us to contact you, we use your personal information to tell you about our products and services and those of our subsidiaries, affiliates, and parent companies and any of their related businesses via email or SMS. However, you will be able to opt out of these communications at any time. We may also share non-personal information with others, such as advertisers, in aggregate anonymous form, which means that the information will not contain any personally identifiable information about you.</p>
				<p>2.2 <b>To restaurants:</b></p>
				<p>2.2.1 When you make a restaurant reservation using our Site, your name and telephone number are provided to that restaurant, so that they can, if necessary, confirm any details about applicable dietary requirements, special preferences or requests, set menus, group bookings etc.</p>
				<p>2.2.2 We will only share the information specified above with the restaurant at which you have made reservations using our Site. Restaurants cannot access information pertaining to diners or dining histories from other restaurants, with the exception that restaurants under the same corporate ownership may elect to share diner information between restaurant properties.</p>
				<p>2.2.3 Restaurants may receive summary reports of feedback from recent diners. If you provide comments about a restaurant (via a review on the Site) these will be shared with that restaurant anonymously. However there is the potential that a restaurant may associate a particular feedback with your dining reservation. You may choose not to be anonymous while submitting your comments, or you may choose to specify your identity or provide contact information such as an email address for the restaurant to use in response to your feedback.</p>
				<p>2.3 <b>Email from restaurants:</b>You may also consent to receive marketing communications from the restaurant at which you've made a reservation. We play no role in the content, frequency, or timing of any restaurant's marketing communications. You may unsubscribe from further communication from a restaurant at any time.</p>
				<p>2.4 <b>Third party offers:</b> We may arrange for carefully selected organisations to send you marketing and promotional information that may be of interest to you. In such circumstances your personal information may be disclosed to these organisations who will agree to be bound by the terms of this Privacy Policy. We will obtain your permission before we send you any such communications.</p>
				<p>2.5 <b>Public (or interactive) areas of the site:</b> Information that you post on or through the public areas of the Site (e.g., chat rooms, bulletin boards and discussion groups) are generally accessible to, and may be collected and used by, others and may result in unsolicited messages or other contact from others. Users of the Site are encouraged to exercise caution when providing personal information about themselves in public areas of this Site.</p>
				<p>2.6 <b>Sale and transfer:</b> In the event of a sale, merger, consolidation, change in control, transfer of substantial assets, reorganisation or liquidation, we may transfer, sell, or assign to third parties information concerning your relationship with us, including without limitation, personally identifiable information that you provide and other information concerning your relationship with us.  You hereby consent to such transfer of your personal information for such purpose.</p>
				<p>2.7 <b>Administration and data management:</b> We may transfer your personal information to third parties under confidentiality obligations when the performance of any service in relation to the activities above is sub-contracted (e.g. the administration of a marketing campaign).</p>
				<p>2.8 <b>Legal purposes:</b> We may disclose your personal information if permitted by law or required to do so by law or where we believe such action is necessary in order to protect or defend our interests or the interests of our customers or users of our Site.</p>
				<p>2.9 <b>Links:</b> This site may contain links or references to other websites outside of our control. Please be aware that we have no control over these sites and our Privacy Policy does not apply to these sites. We encourage you to read the privacy statements and terms and conditions of linked or referenced sites you enter.</p>
				<p>2.10	We will not use your personal information for any purpose (other than as stated above) without your express consent.  We will not use or disclose your personal information to third parties without your consent, unless the use or disclosure is -</p>
				<p>2.10.1 required in order to comply with applicable law, order of court or legal process served on us; and/or</p>
				<p>2.10.2 disclosure is necessary to protect and defend our rights or property.</p>
				<p>2.11	We will be entitled to disclose your personal information to those of our employees and/or third party service providers who assist us to interact with you via our Site or email, and thus need to know your personal information in order to assist us to communicate with you properly and efficiently.  We will ensure that all such employees and/or third party service providers having access to your personal information are bound by appropriate and legally binding confidentiality and non-use obligations in relation to your personal information.</p>
				<p>2.12	We will:</p>
				<p>2.12.1	treat your personal information as strictly confidential;</p>
				<p>2.12.2	take appropriate technical and organisational measures to ensure that your personal information is kept secure and is protected against unauthorised or unlawful processing, accidental loss, destruction or damage, alteration, disclosure or access;</p>
				<p>2.12.3	promptly notify you if we become aware of any unauthorised use, disclosure or processing of your personal information;</p>
				<p>2.12.4	provide you with reasonable evidence of our compliance with our obligations under this policy on reasonable notice and request; and</p>
				<p>2.12.5	upon your request, promptly return or destroy any and all of your personal information in our possession or control.</p>
				<p>2.13	We will not retain your personal information longer than the period for which it was originally needed, unless we are required by law to do so, or you consent to us retaining such information for a longer period.</p>
				<h2>3 Use of cookies</h2>
				<p>3.1 In common with many websites, we use "cookies" to help us gather the following information from visitors to our Site, for example:</p>
				<p>3.1.1 the IP address from which you access the Site;</p>
				<p>3.1.2 the type of browser and operating system used to access the Site;</p>
				<p>3.1.3 the date and time of your access to the Site;</p>
				<p>3.1.4 the pages you visit;</p>
				<p>3.2 A cookie is a small data file that our server sends to your browser when you visit the Site. The use of cookies helps us to assist your use of certain aspects of the Site. You can delete cookies at any time or you can set your browser to reject or disable cookies. Please note however that if you do disable cookies, some functions on the Site may not work correctly.</p>
				<p>3.3 We use information from cookies, for example, to learn about the number of visitors to our Site and the type of technology that our visitors use. Cookies help us to monitor what sort of content is popular and to assess visitors' browsing habits. When a user revisits the Site, we may recognise the user by the cookie and customise the user's experience accordingly. We can use this information to continually improve the content and usability of the Site.  Cookies are not used to personally identify you.</p>
				<p>3.4 We may compile and report to third parties (such as advertisers) aggregate, non-personal statistics about our users in terms of numbers, traffic patterns and related Site information.</p>
				<p>3.5 We do not connect the information collected through cookies with other information that is personally identifiable, unless required or permitted to do so by law or to enforce the Terms &amp; Conditions.</p>
				<h2>4 How we protect your information</h2>
				<p>4.1 We take security seriously and we take reasonable precautions to keep your personal information secure. We have put in place appropriate physical, electronic and managerial procedures to safeguard the information we collect. However, due to the open communication nature of the Internet, we cannot guarantee that communications between you and us, or information stored on our servers, will be free from unauthorised access by third parties.</p>
				<p>4.2 WE WILL NOT BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL INJURY, LOSS OR DAMAGES WHICH MIGHT ARISE FROM THE LOSS, DAMAGE, DESTRUCTION OR UNAUTHORISED OR UNLAWFUL ACCESS OF YOUR PERSONAL INFORMATION, UNLESS SUCH LOSS OR DAMAGES AROSE DUE TO OUR GROSS NEGLIGENCE.</p>
				<h2>5 Your details and contacting us</h2>
				<p>You can check what personal information we hold about you, update your information, ask us to remove your information, correct any inaccuracies in such personal information or ask us questions about our Privacy Policy, by contacting us via email to		<a href="mailto:info@ReserveDine.com">info@ReserveDine.com</a><span style="display: none;">This e-mail address is being protected from spambots. You need JavaScript enabled to view it.		</span>. We will make every effort to respond to your request in a timely manner.</p>
			</div>
		</div>
	</div>
</section>
