
<script type="text/javascript">
$(function() {
	emailValid = "";
	emailObj = $("#emailAddress");
	if($.trim(emailObj.val()) != ""){
		ajaxEmailCall();
	}
	$(".chkAvaliable").click(function(){
		ajaxEmailCall();
	});
	emailObj.blur(function(){
		ajaxEmailCall();
	});
	$("#submit").click(function(){
		emailObj.trigger('blur');
		return emailValid;	
	});
	$("#reset").click(function(){
		var regionTag = $("#region");
	   	$("option",regionTag).remove();
	    var cityTag = $("#city");
		 $("option",cityTag).remove();
	   	var nghTag = $("#neighborhood");
		$("option",nghTag).remove();
			
	});
	function ajaxEmailCall(){
		errorObj = $(".ajaxReturn");
	 var url = "<?php echo $this->url(array('module'=>'User','controller'=>'Client','action'=>'searchforemailexist'),null,true); ?>"
		 errorObj.text(" ");
		 var bValid = true;
		 bValid = bValid && checkRegexp(emailObj,/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/,"<?php echo $this->translate->_("Invalid Email"); ?>");	
		function checkRegexp(o,regexp) {
			if ( !( regexp.test( o.val() ) ) ) {	
				errorObj.text("<?php echo $this->translate->_('Invalid Email'); ?>");
				errorObj.css({'color':'#ED0E19'});
	   			emailValid = false;
	   			return false
			} else{
				return true;
			}
		}
		if(!bValid){
			return false;
		}
	 $.post(url, { email: $.trim(emailObj.val()) },
			   function(data){
			   	data = data.replace(/\s/g,"");
		   		if(data=="t"){
		   			errorObj.text("<?php echo $this->translate->_('Email Address is not available'); ?>");
		   			errorObj.css({'color':'#ED0E19'});
		   			emailValid = false;
		   		}else if(data == "f"){
		   			errorObj.text("<?php echo $this->translate->_('Email Address is available continue  registering'); ?>");
		   			errorObj.css({'color':'#0EED12'});
		   			emailValid = true;
		   		}
		   	});
	}

});
</script>
<script type="text/javascript">
$(document).ready(function(){
	var Loading = "<? echo $this->translate->_('Loading...'); ?>";
	
	$('.captchatd').find("img").attr({'style':'position:relative;bottom:5px;border:2px solid #DBDBD5;'});


	$('.countryflag').click(function(){
		if($(this).parents().eq(1).hasClass('active')){
			$(this).parents().eq(1).removeClass('active');
		}
		if($(this).attr('abbr') != ''){
			$('#countryCode').val($(this).attr('abbr'));
		}
	});
});

</script>
<div id="page-content">
	<section class="container" style="width:700px;margin-bottom:35px;">
		<header>
			<h1 class="page-title"><i class="fa fa-user"></i>  Sign Up Now</h1>
		</header>
		<div class="row">
			<div class="col-md-12">
				<div class="row">
				<form method="post"	action="<?php echo $this->url(array('module'=>'User','controller'=>'Client','action'=>'guestsignup'),null,true); ?>">
					<div class="col-md-6 col-sm-6">
						<div class="form-group">
							<label for="name">Name</label>
							<?php echo $this->form->firstName->setAttrib('placeholder',$this->translate->_('First Name*')); ?>
						</div>
						<!--/.form-group-->
					</div>
					<!--/.col-md-3-->
					<div class="col-md-6 col-sm-6">
						<div class="form-group">
							<label for="Last Name">Last Name</label>
							<?php echo $this->form->lastName->setAttrib('placeholder',$this->translate->_('Last Name')); ?>
						</div>
						<!--/.form-group-->
					</div>
					<!--/.col-md-3-->
					<div class="col-md-6 col-sm-6">
						<div class="form-group">
							<label for="email">Email Address</label>
							<?php 
								echo $this->form->emailAddress->setAttrib('placeholder',$this->translate->_('Email Address*')); echo '<span class="ajaxReturn"></span>';
								?>
						</div>
						<!--/.form-group-->
					</div>
					<div class="col-md-6 col-sm-6">
						<div class="form-group">
							<label for="phone">Phone</label>
							<div class="row">
								<div class="col-md-3"><?php echo $this->form->countryCode->setAttrib('placeholder',$this->translate->_('Code*')); ?></div>
								<div class="col-md-9"><?php echo $this->form->phone->setAttrib('placeholder',$this->translate->_('Phone*'));?></div>
							</div>
						</div>
						<!--/.form-group-->
					</div>
					<!--/.col-md-3-->
					<div class="col-md-6 col-sm-6">
						<div class="form-group">
							<label for="password">Password</label>
							<?php echo $this->form->password->setAttrib('placeholder',$this->translate->_('Password*')); ?>
						</div>
						<!--/.form-group-->
					</div>
					<!--/.col-md-3-->
					<div class="col-md-6 col-sm-6">
						<div class="form-group">
							<label for="password">Confirm Password</label>
							<?php echo $this->form->password_confirm->setAttrib('placeholder',$this->translate->_('Confirm Password*')); ?>
						</div>
						<!--/.form-group-->
					</div>
					<!--/.col-md-3-->
					
					<!--/.col-md-3-->
					<div class="col-md-6 col-sm-6">
						<div class="form-group">
							<label for="Captcha">ENTER CHARACTERS AS SHOWN IN BOX*</label>
							<div class="captchatd" style="float:left;"><?php echo $this->form->captcha;?></div>
						</div>
						<!--/.form-group-->
					</div>
					<div class="clear"></div>
					<section>
						<div class="form-group">
                        	<button id="submit" class="btn btn-default pull-right" id="register" type="submit">Sign Up</button>
						</div>
					</section>					
				</div>
				</form>
			</div>
		</div>
	</section>
</div>		