<style type="text/css">
	.search-bar.horizontal .main-search .input-row {
  margin-bottom: 10px !important;
}
</style>
<?php 
$guestData = $this->guestData;

?>
<script>
	$('select').selectpicker('render');
	$(function()
	{
		var emailpTr = '';
		$('.edit').live('click',function(){
			emailpTr = $(this).parents('tr');
			email =$('.email',emailpTr).text();
			 var userid =$('.userid',emailpTr).text();
			emailEdit(email,userid);
		});
		$('#editEmailSubmit').live('click',function(){
			//alert("called");
			var currentForm = $(this).parents("form");
			var currformid = currentForm.attr("id");
        	FormValues =new FormData($('#'+currformid)[0]);
        	var url = "<?php echo $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'updateguestinfo'),'default',true);?>"; 
        	$.ajax({
	          url: url,   
	          type: "POST", 
	          data:FormValues, 
	          contentType: false,  
	          cache: false,          
	          processData:false,     
	          success: function(data){
	          	console.log(data);
	          	if(data==1)
	          	{
	          		location.reload();
	          		alert("Email Updated");
	          		$(".modal-close").click();
	          		location.reload();
	          	}
	          }
			
			});
			return false;
		});
		$('.editpass').live('click',function(){
			$("#password").parent().find('.errors').remove();
			$("#password_confirm").parent().find('.errors').remove();
			var pTr = $(this).parents('tr');
			var userid =$('.userid',pTr).text();
			passwordEdit(userid);
			return false;			
		});
		$('#editPassSubmit').live('click',function(){
			if($(".pass").val()!=$(".confirmpass").val())
      		{
        	alert("password and  confirm password must be same");
        	return false;
      		}
			var currentForm = $(this).parents("form");
			var currformid = currentForm.attr("id");
        	FormValues =new FormData($('#'+currformid)[0]);
        	var url = "<?php echo $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'updateguestinfo'),'default',true);?>"; 
        	$.ajax({
	          url: url,   
	          type: "POST", 
	          data:FormValues, 
	          contentType: false,  
	          cache: false,          
	          processData:false,     
	          success: function(data){
	          	console.log(data);
	          	if(data==1)
	          	{
	          		alert("Password Updated");
	          		$(".modal-close").click();
	          		location.reload();
	          	}
	          }
			
			});
			return false;
		});


	});
	function emailEdit(email,userid){
			var htmlDia = '<div class="modal-window fade_in"><div class="modal-wrapper">';
	        htmlDia += '<h2>Edit Guest Email Address</h2>';
	       	htmlDia += '<div class="modal-body"><div class="modal-content">';
	       	htmlDia += '<form data-toggle="validator" role="form"  method="post"  id="editEmailForm">';
	       	htmlDia += '<div class="form-group"><label><?php echo $this->translate->_("Email");?><span class="star"> * </label>';
	       	htmlDia += '<input type="text" maxlength=40 name="emailAddress" id="emailAddress" class="email required" value="'+email+'"></div><input type="hidden"  value="'+userid+'" id="id" name="id" />';
	       	htmlDia += '<div class="form-group"><button class="sml-btn1 pull-right" id="editEmailSubmit" >Submit</button></div></form>';
			htmlDia += '</div></div><div class="modal-close"><img src="/images/close.png"></div></div><div class="modal-background fade_in"></div></div>';
	        $('body').append(htmlDia);
		}
	function passwordEdit(userid){
			var htmlDia = '<div class="modal-window fade_in"><div class="modal-wrapper">';
			htmlDia += '<h2><?php echo $this->translate->_("Edit Guest Password"); ?></h2>';
			htmlDia += '<div class="modal-body"><div class="modal-content">';
			htmlDia += '<form data-toggle="validator" role="form" method="post"  id="passwordEmailForm">';
			htmlDia += '<div class="form-group"><label><?php echo $this->translate->_("Password");?><span class="star"> * </label><input type="password"  class="pass" name="password" id="password" value="" class="inp1" maxlength="20" /></div>';
			htmlDia += '<div class="form-group"><label><?php echo $this->translate->_("Confirm Password");?><span class="star"> * </label><input type="password" class="confirmpass" name="password_confirm" id="password_confirm" value="" class="inp1" maxlength="20" /></div>';
			htmlDia += '<input type="hidden" name="userid" class="userid" value="'+userid+'" id="userid" /><div class="form-group">';
			htmlDia += '<button class="sml-btn1 pull-right" id="editPassSubmit" >Submit</button>';
			htmlDia += '</div>';
			htmlDia += '</form></div></div><div class="modal-close"><img src="/images/close.png"></div></div><div class="modal-background fade_in"></div></div>';
			$('body').append(htmlDia);
		}	
</script>

				<div class="navbar navbar-default" role="navigation">
					<div class="container">
						<div class="collapse navbar-collapse">
							<ul class="nav navbar-nav">
								<li>
									<a href="#" class="dropdown-toggle active" data-toggle="dropdown" ><strong>Restaurant Management<b class="caret"></b></strong></a>
									<ul class="dropdown-menu multi-level">
										<li><a href="<?php echo $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'firmregistration'),null,true);?>">Add Restaurant</a></li>
										<li><a href="<?php echo $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'managerestaurant'),null,true);?>">Manage Restaurant</a></li>
									</ul>
								</li>
								<li><a href="#" class="dropdown-toggle active" data-toggle="dropdown" >Users<b class="caret"></b></a>
									<ul class="dropdown-menu multi-level">
										<li><a href="<?php echo $this->url(array('module'=>'User','controller'=>'Client','action'=>'manageguests'),null,true);?>">Customers</a></li>
									</ul>
								</li>
								<li><a href="#" class="dropdown-toggle active" data-toggle="dropdown" >Base Data Management<b class="caret"></b></a>
									<ul class="dropdown-menu multi-level">
										<li><a href="<?php echo $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'countrybdm'),null,true);?>">Country</a></li>
										<li><a href="<?php echo $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'citybdm'),null,true);?>">City</a></li>
										<li><a href="<?php echo $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'locationbdm'),null,true);?>">Location</a></li>
										<li><a href="<?php echo $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'pricebdm'),null,true);?>">Price</a></li>
										<li><a href="<?php echo $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'cusinebdm'),null,true);?>">Cusine</a></li>
										<li><a href="<?php echo $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'diningbdm'),null,true);?>">Dining</a></li>
										<li><a href="<?php echo $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'tagsbdm'),null,true);?>">Tags</a></li>
									</ul>
								</li>
								<li><a href="#" class="dropdown-toggle active" data-toggle="dropdown" >Reservations<b class="caret"></b></a>
									<ul class="dropdown-menu multi-level">
										<li><a href="<?php echo $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'showresbooking'),null,true);?>">Manage Reservation</a></li>
									</ul>
								</li>
							</ul>
						</div><!--/.nav-collapse -->
					</div>
				</div>
						   <section class="sub-header">
		                <div class="search-bar horizontal collapse" id="redefine-search-form" style="height: 0px;">
		<div class="content">
		    <div class="container">
		        <form class="main-search inputs-3" role="form" method="post" action="?">
		            <div class="input-row">
		                <div class="form-group">
		                 
		                </div><!-- /.form-group -->
		                <div class="form-group">
		                    <?php echo $filterForm->resname; ?>
		                </div>
		                <!-- /.form-group -->
		                <!-- /.form-group -->
		                <div class="form-group">
		                    <?php echo $filterForm->resemail; ?>
		                </div>
		                <!-- /.form-group -->
		                </div>

		                <div class="input-row">
		                <div class="form-group">
		                  	<?php echo $filterForm->rescountry_id; ?>
		                </div>
		                <!-- /.form-group -->
		                <!-- /.form-group -->
		                <div class="form-group">
		                  	<?php echo $filterForm->rescity_id; ?>
		                </div>
		                <!-- /.form-group -->
		                <!-- /.form-group -->
		                <div class="form-group">
		                  	<?php echo $filterForm->reslocation_id; ?>
		                </div>

		                <!-- /.form-group -->
		                <div class="form-group" style="width: initial;">
		                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
		                </div>
		                <!-- /.form-group -->
		            </div>
		        </form>
		        <!-- /.main-search -->
		    </div>
		    <!-- /.container -->
		</div>



		</div>
		                <!-- /.search-bar -->
		                <div class="breadcrumb-wrapper">
		                    <div class="container">
		                        <div class="redefine-search">
		                            <a href="#redefine-search-form" class="inner collapsed" data-toggle="collapse" aria-expanded="false" aria-controls="redefine-search-form">
		                                <span class="icon"></span>
		                                <span>Redefine Search</span>
		                            </a>
		                        </div>
		                        <ol class="breadcrumb">
		                            <li><a href="index-directory.html"><i class="fa fa-home"></i></a></li>
		                            <li><a href="#">Page</a></li>
		                            <li class="active">Detail</li>
		                        </ol>
		                        <!-- /.breadcrumb-->
		                    </div>
		                    <!-- /.container-->
		                </div>
		                <!-- /.breadcrumb-wrapper-->
		            </section>
                <section class="container">
                    <div class="row">
                        <!--Company Detail Content-->
                        <div class="col-md-12">
                            <header>
                                <h1 class="page-title">Manage Guests</h1>
                            </header>
                            <hr>
							<header>
                                <h1>Restaurants</h1>
                            </header>
							<table class="table">
								<tr>
									<th>Id</th><th>First Name</th><th>Last Name</th><th>Email</th><th>Phone</th><th>Status</th><th>Actions</th>
								</tr>
								<?php 
								//print_r($guestData);die();
								foreach ($guestData as $guest):?>
								<tr><td class="userid"><?php  echo $guest['cusid'] ?></td>
<td><?php  echo $guest['cusfirst_name'] ?></td><td><?php echo $guest['cuslast_name'];?></td><td class="email edit"><?php echo $guest['useremail'] ?></td><td><?php echo $guest['cusmobile'];?></td><td name="statusTd">
										<?php if($guest['cus_status']==1)
										  {
										  	echo 'Active';
										  }
										  else
										  {
										  	echo 'In-Active';
										  }
										  ?>
									</td>
									<td>
										  <a class = "editpass" href=""><i class="fa fa-edit"></i> Edit</a>&nbsp; | &nbsp;
										  <?php 
										  if($guest['cus_status']==1)
										  {
										  	echo ' <a class="statusChangeButton" href="#" data-id="'.$guest['cusid'].'" data-value="'.$guest['cus_status'].'"><i class="fa fa-times"></i>De-Activate</a>';
										  }
										  else
										  {
										  	echo ' <a class="statusChangeButton" href="#" data-id="'.$guest['cusid'].'" data-value="'.$guest['cus_status'].'"><i class="fa fa-times"></i>Activate</a>';
										  }
										  ?>
										  &nbsp; | &nbsp; <a href="#"><i class="fa fa-info-circle"></i> Info</a>
									</td>
									
								</tr>
							<?php endforeach ?>		
							</table>
							<div class="clear"></div>
							<hr>
                        </div>
                        <!-- /.col-md-8-->
                    </div><!-- /.row-->
                </section>
 <script type="text/javascript">
$(function()
{
	$(".statusChangeButton").click(function()
	{
		var value = parseInt($(this).attr("data-value"));
		console.log(value);
		var id = parseInt($(this).attr("data-id"));
		var target = $(this);
		var url = "<?php echo $this->url(array('module'=>'User','controller'=>'Client','action'=>'updateguestajax'),null,true);?>";
		$.post(url, {data:value,updateId:id}, function(data)
		{
			
			if(data!=false)
			{
				$(target).attr("data-value",data);
				var parentTr = $(target).parents('tr');
				if(data==2)
				{
					$(target).html('<i class="fa fa-times"></i>Activate');
					parentTr.find("td[name='statusTd']").each(function()
					{
						$(this).html("In-Active");
					});

				}
				else
				{
					$(target).html('<i class="fa fa-times"></i>De-Activate');
					parentTr.find("td[name='statusTd']").each(function()
					{
						$(this).html("Active");
					});
	
				}
			}
		});
		return false;
	});
});


 </script> 