
<script>
$(document).ready(function(){
	
	
});
</script>

<style>

.search-bar.horizontal .main-search .input-row {
  margin-bottom: 10px !important;
}
.info{
	padding:10px;
	background: #ececec;
	text-align: center;
	text-transform: uppercase;
	margin-bottom:20px;
}
.col-xs-offset-1{margin-left:6%;}
.info h3{
	margin-bottom: 6px;
	font-size: 22px;
}
.input_form {
	display: inline-block;
	font-size: 12px;
	padding: 5px;
	height: 35px;
	line-height: 16px;
	border: 1px #b2b6bb solid;
	background: #fff;
	color: #151515;
	text-overflow: ellipsis;
	white-space: nowrap;
	box-sizing: border-box;
	-webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	border-radius: 5px;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
	-khtml-border-radius: 5px;
	box-shadow: inset 0 2px 5px rgba(0, 0, 0, .1);
	-moz-box-shadow: inset 0 2px 5px rgba(0, 0, 0, .1);
	-khtml-box-shadow: inset 0 2px 5px rgba(0, 0, 0, .1);
	-webkit-box-shadow: inset 0 2px 5px rgba(0, 0, 0, .1);
	width:100%;
	font-family: Century Gothic, Arial, Helvetica, sans-serif;
}
</style>

<section class="sub-header">
    <div class="search-bar horizontal collapse" id="redefine-search-form" style="height: 0px;">
		<div class="content">
			<div class="container">
			    <form class="main-search inputs-3" role="form" method="post" action="?">
			        <div class="input-row">
			            <div class="form-group">
			                	<?php echo $this->form->id; ?>
			            </div><!-- /.form-group -->
			            <div class="form-group">
			                <?php echo $this->form->name; ?>
			            </div>
			            <!-- /.form-group -->
			            <!-- /.form-group -->
			            <div class="form-group">
			                <?= $this->form->startdate;?>
			            </div>
			            <!-- /.form-group -->
			        </div>

			        <div class="input-row">
			            <div class="form-group">
			              	<?= $this->form->enddate?>
			            </div>
			            <div class="form-group">
			              	<?php echo $this->form->status ?>
			            </div>
			            <div class="form-group" style="width: initial;">
			                <button type="submit" class="btn btn-default submitBtn"><i class="fa fa-search"></i></button>
			            </div>
			            <!-- /.form-group -->
			        </div>
			    </form>
			    <!-- /.main-search -->
			</div>
		<!-- /.container -->
		</div>
	</div>
	<div class="breadcrumb-wrapper">
        <div class="container">
            <div class="redefine-search">
                <a href="#redefine-search-form" class="inner collapsed" data-toggle="collapse" aria-expanded="false" aria-controls="redefine-search-form">
                    <span class="icon"></span>
                    <span>Redefine Search</span>
                </a>
            </div>
            <ol class="breadcrumb">
                <li><a href="index-directory.html"><i class="fa fa-home"></i></a></li>
                <li><a href="#">Page</a></li>
                <li class="active">Detail</li>
            </ol>
            <!-- /.breadcrumb-->
        </div>
        <!-- /.container-->
    </div>
    <!-- /.breadcrumb-wrapper-->
</section>

<section class="container">
    <div class="row">
        <!--Company Detail Content-->
        <div class="col-md-12">
            <header>
                <h1 class="page-title">Manage Inquiry</h1>
            </header>
            <hr>
			<header>
                <h1>Restaurants</h1>
            </header>
            <?php 
				if($this->resultSet && count($this->resultSet)){

					echo '<table class="table" style="margin: 0px; width="100%">
						 	<tr>
						 	    <th width="5%">'.$this->translate->_("Id").'</th>		
								<th width="15%">'.$this->translate->_("Name").' </th>					
								<th width="30%">'.$this->translate->_("Phone or Email").'</th>			
								<th width="10%">'.$this->translate->_("Contact Type").'</th>		
								<th width="10%">'.$this->translate->_("PostedOn").'</th>
								<th width="20%">'.$this->translate->_("Status").'</th>
								<th width="10%">'.$this->translate->_("Action").'</th>
							</tr>';
					foreach($this->resultSet as $result){
						echo '<tr>';
						if($result->company_id != 1){
							echo '<td class="contactid" style="color:red;">'.$result->id.'</td>';
						}else{
							echo '<td class="contactid">'.$result->id.'</td>';
						}
						
						echo '<td><a class="a1 conname" id="'.$result->id.'" type="'.$result->contacttype.'" >'.$result->contactname.'</a></td>';
						if($result->phone && !$result->email){
							echo '<td><label>'.$this->translate->_("Phone:").' </label>'.$result->phone.'</td>';
						}else if($result->email && !$result->phone){
							echo '<td><label>'.$this->translate->_("Email :").' </label>'.$result->email.'</td>';
						}else{
							echo '<td><label>'.$this->translate->_("Phone:").' </label>'.$result->phone.'<br/>'.'<label>'.$this->translate->_("Email :").' </label>'.$result->email.'</td>';
						}
						if($result->ipaddress){
							echo '<td>'.$result->contacttype.'</br>ip: '.$result->ipaddress.'</td>';
						}else{
							echo '<td>'.$result->contacttype.'</td>';
						}	
						
						$Date = explode("-",$result->postedon);
				
						$s = mktime(0,0,0,$Date[1],$Date[2],$Date[0]);
				//		$frzDate = date('m-d-Y',$s);
						$frzDate = date('d M Y',$s);
						echo '<td>'.$frzDate.'</td>';
						$Url = $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'deactreachus','id'=>$result->id),null,true);
						if($result->enquiry_status_id != 6){
							if($result->description != '')
							{
								echo '<td>'.$result->description.'</td>';
							}else{
								echo '<td>Open</td>';
							}
							echo '<td><a class="editlog a1"><i class="fa fa-edit"></i>'.$this->translate->_("AddLog").'<br/></a>';
							if($result->enquiry_status_id != 1){
							echo '<a class="viewlog a1"><i class="fa fa-edit"></i>'.$this->translate->_("ViewLog").'<br/></a>';
							}
							echo ' <a class="a1" href="'.$Url.'"><i class="fa fa-times"></i>Close</a></td>';
						}else{
							echo '<td>'.$this->translate->_("Closed").'</td>';
							echo '<td><a class="viewlog a1"><i class="fa fa-edit"></i>'.$this->translate->_("ViewLog").'</a></td>';
						}
						echo '</tr>';
					}
					echo '<tr><td class="tl" colspan="8">';
					echo $this->paginationControl($this->resultSet,
				    			'Sliding','my_pagination_control.phtml');
					echo '</td></tr>';							
					echo '</table>';
				
				}else{
					echo '<span class="red"><b>'.$this->translate->_("No records found.").'</b></span>';
				}
			?>
        </div>	
    </div>   
</section> 
