	<link rel="stylesheet" href="/css/jquery.mCustomScrollbar.css" type="text/css">
	
	<style type="text/css">
	.dot-extensions{
    width:160px;
    white-space: nowrap;
    overflow:hidden !important;
    text-overflow: ellipsis;
  	}
.item .image a > img, .item .image > .inner > img
{
	height: 100%;

}
	.likeButton
	{
			margin-right: 5px !important;
			color: red;
	}
	.likeButton:hover
		{
			border :1px solid white;
			color: black;
		}
		.other-filter-selected
		{
			color:white;
			background-color:#ac181d; 
		}
		.filter-btn:hover
		{
			color:black;
		}
		.others-option-selected
		{
			border-color:#ac181d;
		}
		.view-all .filter-container{width:100% !important;}
		.view-all {
				    padding: 10px;
				   border-top: 0px solid rgba(0,0,0,.1);
				    background-color: #f4f4f4;
				}
		.filter-container .label{padding:10px 0;}
		 .modal-window .modal-wrapper .modal-body .modal-content {
    display: block;
}
ul{padding-left:0;}
 .sml-btn1 {
    font-size: 14px;
    border: 0px solid #ff513f;
    padding: 6px;
    border-radius: 3px;
    margin-left: 10px;
    color: #fff;
    background: #2d2d2d;
    width: 100%;
    text-align: center;
}
.item .wrapper figure{height:16px;overflow:hidden;}
 .res-rating {
    color: #2d2d2d;
    cursor: default;
    border-radius: 5px;
    font-size: 16px;
    height: 26px;
    line-height: 28px;
    text-align: center;
    width: 26px;
    margin: 0 auto;
    background: #fff;
    display: block;
    margin-bottom: 12px;
    border: 1px solid #2d2d2d;
}
 .modal-window{
  left: 0;
  }
  .red
  {
  	color: black !important;
  }
 .map-canvas .results.list li .item .wrapper{padding:4px 10px;}
 .modal-window .modal-wrapper .modal-body {
  background-color: #3a3a3a;
  display: table;
  font-size: 14px;
  margin-top: 0px;
  padding: 0;
  text-align: left;
  width: 580px;
 }
 .modal-window .modal-wrapper{
  top:52px;
  }
 .modal-window .modal-wrapper .modal-body .gallery {
        width: 580px;
  overflow:hidden;
  height: 300px;
 }
 .modal-window .modal-wrapper .modal-body .modal-content {
 display:block;
 }
 form.main-search{width:780px;}
 .show-tick .dropdown-toggle{
  padding:8px;
  border-radius:3px 0 0 3px !important;
  background:#fff url(assets/img/location.png) no-repeat 8px 8px !important;
  padding-left: 30px !important;
  }
 .form-group1 .show-tick .dropdown-toggle {
  padding: 8px;
  border-radius: 3px !important;
  background: none !important;
  padding-left: 0px !important;
  color: #fff;
 }
 .form-group1{
  margin-left:20px;
  width:120px !important
  }
 .form-group1 .bootstrap-select .selectpicker .caret:after{
  color:#fff;
  }
 #location{
  padding:8px;
  background:#fff url(assets/img/search1.png) no-repeat 4px 8px;
  padding-left: 30px !important;
  }
 .search1{ 
  border-radius:0 3px 3px 0;
  padding:8px;
 }
 #counter{
 background:url(assets/img/features_bg1.jpg) no-repeat top center;
 }
 .search-bar.horizontal .main-search .input-row{
  margin-bottom:0;
  }
 form.main-search{
  padding: 2px 0 0 0;
  }
 .item.list .wrapper{
  display:inline-block;
  width:67%;
  }
 .modal-window .modal-wrapper .modal-close {
  cursor: pointer;
  position: absolute;
  right: -30px;
  top: 0px;
  z-index: 3;
 }
 .modal-window .modal-wrapper{
 left:-20px;
 box-shadow: 10px 6px 10px rgba(0, 0, 0, 0.25);
  }
 .item-review a{border:0px solid #fff;    margin: 0px 4px 0 0;}
 .modal-window .modal-wrapper .modal-body .gallery .image .type {
    background-color: rgba(255, 255, 255, 0.74);
    padding: 4px;
    position: absolute;
    bottom: 0;
    left: 0;
    z-index: 2;
    width: 100%;
    / z-index: 1; /
}
.model-popUp .selectpicker, .model-popUp .form-control{
	 border:1px solid #ccc;
	 color:#333
	 }
	.tc{text-align:center;}
	.model-popUp .button {
	    border-style: solid;
	    border-width: 0;
	    cursor: pointer;
	    font-weight: 400;
	    line-height: normal;
	    margin: 0 0 1rem;
	    position: relative;
	    text-decoration: none;
	    text-align: center;
	    outline: 0;
	    border-radius: 3px;
	    display: block;
	    background-color: #ED1C24;
	    border-color: #b8222d;
	 box-shadow: 0 0 0 1px #ED1C24;
	 cursor:pointer;
	 width:100%;
	    color: #fff;
	    -webkit-transition: background-color 300ms ease-out;
	    -moz-transition: background-color 300ms ease-out;
	    transition: background-color 300ms ease-out;
	    padding: .875rem 1.75rem .9375rem;
	    font-size: 1rem;
	}
	.list-left{
	 padding:0;
	}
	.list-left>li {
	    float: left;
	    margin-right: 1rem;
	 list-style:none;
	}
	.dtp-button {
	    border-radius: 3px;
	    position: relative;
	    padding: .7rem 1.5rem;
	    color: #fff;
	    background: #131313;
	    display: inline-block;
	    line-height: 1;
	    margin-bottom: 12px;
	}
	.booking_dtl li {
	    display: inline-block;
	    margin-right: 30px;
	}.booking_dtl {
	    margin-top: 40px;
	}
	.list-unstyled {
	    padding-left: 0;
	    list-style: none;
	}
	.dblock {
	    display: block;
	}
	.mrgn_btm10 {
	    margin-bottom: 10px !important;
	}
	.bold {
	    font-weight: bold;
	 color:#444;
	}
	.reservSel{
		background: red;
	}
	.likeButton
	{
			margin-right: 5px !important;
			color: red;
	}
	.likeButton:hover
		{
			border:1px solid white;
			color: black;
		}
	.fade_in
	{
	/*-webkit-transition-delay: 3s;
	-moz-transition-delay: 3s;
	-khtml-transition-delay: 3s;  
    transition-delay: 3s;*/
	}
	.restimes
	{
		display: block;
	}
	.red
	{
		color: black!important;
		z-index: 10001;
	}
	.reserv-modal-close{
		cursor: pointer;
	    position: absolute;
	    right: -30px;
	    top: 0px;
	    z-index: 3;
	}
	.isSelected i,.isSelected a 
	{
		color:red;
	}
 </style>
	<script>
    // Render Owl carousel gallery

   $(function()
   {
   	 var _rtl = false;
    drawOwlCarousel(_rtl);

    // Render Rating stars

    rating('.modal-window');

    // Remove modal element form DOM

    $('.modal-window .modal-background, .modal-close').live('click',  function(e){
        $('.modal-window').addClass('fade_out');
        setTimeout(function() {
            $('.modal-window').remove();
        }, 300);
    });
});
</script>

	<script type="text/javascript">
	var isLoggedIn = "<?php echo $this->isLoggedIn; ?>";
	var userid = "<?php echo $this->userid; ?>"
		$(document).ready(function(){
			$(".search-option").val("<?= $this->searchOrder?>").selectpicker('refresh');
			$('.fbsignup').live('click',function(){
				var url = "<?php echo $this->url(array('module'=>'User','controller'=>'Client','action'=>'signinfromwidget'),'default',true); ?>";
				var widgetlink = "<?php echo $this->url(); ?>";
				$.post(url,{widgetlink:widgetlink},function(data){
					if(data == 'auth'){
						window.location = widgetlink;
					}else{
						window.open(data,'fblog', "height=300,width=500");
					}
				});
			});
			
			getFiltersJson();
			$('select.filter').change(function()
			{
				var filterValues = getFilterValues();
				setFilterData(filterValues);		
			});
			$('.openNow').click(function()
			{
				if($(this).attr("data-value")=="false")
				{
					$(this).addClass('isSelected');
					$(this).attr('data-value',"true");
				}
				else
				{
					$(this).removeClass('isSelected');
					$(this).attr('data-value',"false");
				}
				$('select.filter').change();
				return false;
			});
			$(".filter-btn").click(function()
			{
				var className = 'other-filter-selected';
				if($(this).hasClass(className))
				{
					$(this).removeClass(className);
				}
				else
				{
					$(this).addClass(className);
				}
				return false;
			});
			$(".other-filter-submit").click(function()
			{
				if($(".other-filter-selected").length >0)
					{
						$(".btn-group bootstrap-select framed").addClass("others-option-selected");
					}
				setFilterData(getFilterValues());	
			});
			 $(".likeButton").live('click',function()
		    {
		    	var btn = $(this);
		    	if($(this).hasClass("red"))
		      	{
		      		$(this).removeClass("red");
		      	}
		      	else
		      	{
		      		$(this).addClass("red");
		      	}
		       var loggedin ="<?php echo $this->isLoggedIn ?>" ; 
	    	var userid =    "<?php echo $this->userid ?>" ;     
	    	if(loggedin)
	    	{
		    	var resid = parseInt($(this).attr("data-id"));
		    	var parentArray = Array();
		    	var url = "<?php echo $this->url(array('module'=>'Restaurant','controller'=>'Restaurant','action'=>'shortlistinsert'),'default',true);?>";
		    	$.post(url,{perform:"insert",resid:resid,userid:userid},function(dataid)
				{	
					if(dataid==true)
					{
						$(onloadjsondata.data).each(function()
						{
							if($(this)[0].id==resid)
							{
									addLikeItem($(this)[0]);
							}
						});
					}
					else
					{
						removeLikeItem(resid);
					}
				});
				return false;
	    	}
	    	else
	    	{	
		      var resid = parseInt($(this).attr("data-id"));
		      var jsonData = onloadjsondata['data'];
		      var currentLike = Array();
		      for(var i in jsonData)
		      {
		       if(jsonData[i]['id']==resid)
		       {
		        	currentLike = jsonData[i];
		       }
	     	 }
		      if((localStorage.getItem("shortlistDetails")==null)||(localStorage.getItem("shortlistDetails")==""))
		      {
			       var parentArray = Array();
			       var likesData = {id:$(this).attr("data-id")};
			       parentArray.push(currentLike);
			       localStorage["shortlistDetails"]=JSON.stringify(parentArray);
			       addLikeItem(currentLike);
		      }
		      else
		      {
			       var strLikes = localStorage.getItem("shortlistDetails");
			       var currentId = $(this).attr("data-id");
			       var likesData = Array();
			       likesData = JSON.parse(strLikes);
			       var listed = false;
			       var removedIndex ;
			       for(var i in likesData)
			       {
				        if(likesData[i]['id']==currentId)
				        {
				         removedIndex = i;
				         listed = true;
				        }
			       }
				       if(!listed)
				       {
				        likesData.push(currentLike);
				        localStorage["shortlistDetails"]=JSON.stringify(likesData);
				         addLikeItem(currentLike);
				       }
				       else
				       {
				        likesData.splice(removedIndex,1);
				        localStorage["shortlistDetails"]=JSON.stringify(likesData);
				        $("i[data-id ='"+resid+"']").removeClass("red");
				        removeLikeItem(resid);
				       }
		      }
		      	
	      return false;
	       	}
		    });
			$(".resliked").live('click',function(event)
	  		{   var resid = $(this).attr('data-id');
		  			//alert(data);
			    if(isLoggedIn)
			    {
			      

			      var url = "<?php echo $this->url(array('module'=>'Restaurant','controller'=>'Restaurant','action'=>'reslikes'),'default',true);?>";
			      //var userid = "<?php echo $this->userid;?>";
			      //var resid = "<?php echo $this->resid;?>";
			      $.post(url,{perform:"like",userid:userid,resid:resid},
			      function(data){
		            if(data.length>0)
		            {
		              data = JSON.parse(data);
		              $(".resliked").html('<a href="#" class="pull-left white resliked"><i class="fa fa-thumbs-up white"></i>'+data['res_likes']);
		              $(".resdisliked").html('<a href="#" class="pull-left white resdisliked"><i class="fa fa-thumbs-down white"></i>'+data['res_dislikes']);
		            }		           
			           // window.reload();
			       });
			   // return false;
			    }
			    else
			    {
			    Login();
			    //return false;
			    }
 			});//quickView(id);
			$(".resdisliked").live('click',function(event)
	  		{   var resid = $(this).attr('data-id');
		  			//alert(data);
			    if(isLoggedIn)
			    {
			      var url = "<?php echo $this->url(array('module'=>'Restaurant','controller'=>'Restaurant','action'=>'reslikes'),'default',true);?>";
			      //var userid = "<?php echo $this->userid;?>";
			      //var resid = "<?php echo $this->resid;?>";
			      $.post(url,{perform:"dislike",userid:userid,resid:resid},
			      function(data){
		            if(data.length>0)
		            {
		              data = JSON.parse(data);
		              $(".resliked").html('<a href="#" class="pull-left white resliked"><i class="fa fa-thumbs-up white"></i>'+data['res_likes']);
		              $(".resdisliked").html('<a href="#" class="pull-left white resdisliked"><i class="fa fa-thumbs-down white"></i>'+data['res_dislikes']);
		            }		           
			           // window.reload();
			       });
			   // return false;
			    }
			    else
			    {
			    Login();
			    //return false;
			    }
 			});
			$('.resReserv').live('click',function(){
				var loggedin = "<?php echo $this->isLoggedIn ?>" ;
			    if(loggedin)
			    {
					resid = $('.resListResName',$(this).parents('.modal-body')).attr('reslistedRestaurant');
					var htmlContent = '';
					var apiUrl = "http://www.dinedesk.com/Associate/Associate/partnersapi/key/53832ab7a845c/apiname/GMT/restaurantid/"+resid;
					if(resid != 'null'){
						$.post(apiUrl,function(gmtdata){
							if(gmtdata['status'] == 'Y'){
								htmlContent +='<div class="modal-window fade_in reserv-modal-window">';
								htmlContent +='<div class="modal-wrapper" style="top:50;">';
								htmlContent +='<div class="modal-body" style="width:800px;">';
							htmlContent += '<div class="modal-content"> ';
							htmlContent += '<div class="row"> ';
							htmlContent += '<div class="col-md-6">';
							htmlContent += '<img class="tc" src="/images/loyalty-points.png" />';
							htmlContent += '<img src="/images/discounts.png" /> ';
							htmlContent += '</div> ';
							htmlContent += '<div class="col-md-6 reservModal"> ';
								htmlContent +='<div class="reservSearch">';
								htmlContent += '<h1 class="title tc">RESERVE YOUR TABLE NOW</h1><hr/>';
								htmlContent += '<form class="reservForm">';
								htmlContent += '<div class="row">';
								htmlContent +='<div class="col-md-12">';
								htmlContent += '<div class="form-group"><label>Party Size:</label>';
								htmlContent += '<select id="reservPax" name="reservPax" class="form-control" style="border:0px solid #fff !important">'
								for(var i = 1; i <= 20; i++){
									htmlContent += '<option>'+i+'</option>';
								}
								htmlContent += '</select></div></div>';
								htmlContent += '<div class="col-md-12">';
								htmlContent += '<div class="form-group"><label>Date:</label>';
								htmlContent += '<div class="input-group date"><input type="text" data-provide="datepicker" id="reservDate" class="form-control"><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div></div>';
						        htmlContent += '<div class="col-md-12">';
						        htmlContent += '<div class="form-group"><label>Type:</label>';
								htmlContent += '<select id="reservDiningType" class="form-control" style="text-transform:capitalize">';
								var diningType = gmtdata['mealtypes'];
								for(var item in diningType){
									if(diningType[item]){
										htmlContent += '<option value="' +item+ '" >'+diningType[item]+'</item>';
									}else{
										htmlContent += '<option disabled="disabled" value="' +item+ '" >'+diningType[item]+'</item>';
									}						
								}
								htmlContent += '</select></div></div>';
								htmlContent += '<div class="dnone"><input type="hidden" id="reservResid" name="reservResid" value="'+resid+'"/><input type="hiddden" id="reservAction" name="reservAction" value="search"/></div>'
								htmlContent += '</div>';
								htmlContent += '<div class="gap"></div>';
								htmlContent += '<div class="row"><div class="col-md-12"><a class="btn btn-default" id="reservSubmit" style="width:100%; " attr="source">Reserve Now</a></div><div class="col-md-4"></div></div></form>';

								//htmlContent += '<div class="form-group"><label>Date:</label>';
								//htmlContent += '<input type="text" placeholder="Date" maxlength="40" class="inp1 date" value="" id="reservDate" name="reservDate"></div>';
								
								
								/*for(var it in mainListData.data){
									if(mainListData.data[it].id == resid){
										htmlContent += '<div class="form-group"><label>Type:</label>';
										var diningType = mainListData.data[it].item_specific.dining_type;
										htmlContent += '<select id="reservDiningType" class="form-control" style="text-transform:capitalize">';
										for(var item in diningType){
											if(diningType[item]){
												htmlContent += '<option attr="' +item+ '" >'+item+'</item>';
											}else{
												htmlContent += '<option disabled="disabled" attr="' +item+ '" >'+item+'</item>';
											}						
										}
										htmlContent += '</select>';
									}
								}
								
								htmlContent += '</div></div>';*/
								
								
								htmlContent +='</div>';
								htmlContent +='<div class="reserv-modal-close"><img src="/images/close.png"></div>';
								htmlContent +='</div>';
								htmlContent +='</div>';
								htmlContent +='</div>';
								htmlContent +='</div>';
								htmlContent +='</div>';
								$('body').append(htmlContent);

								var _rtl = false;
							    drawOwlCarousel(_rtl);

							    // Render Rating stars

							    rating('.modal-window');

							    // Remove modal element form DOM

							    $('.reserv-modal-close').live('click',  function(e){
							        $('.reserv-modal-window').addClass('fade_out');
							        setTimeout(function() {
							            $('.reserv-modal-window').remove();
							        }, 300);
							    });

							}
						});
					}else{
						resid = 1;
						htmlContent +='<div class="modal-window fade_in">';
						htmlContent +='<div class="modal-wrapper" style="top:50;">';
						htmlContent +='<div class="modal-body" style="width:800px;">';
							htmlContent += '<div class="modal-content"> ';
							htmlContent += '<div class="row"> ';
							htmlContent += '<div class="col-md-6">';
							htmlContent += '<img class="tc" src="/images/loyalty-points.png" />';
							htmlContent += '<img src="/images/discounts.png" /> ';
							htmlContent += '</div> ';
							htmlContent += '<div class="col-md-6 reservModal"> ';
						htmlContent +='<div class="reservSearch">';
						htmlContent += '<h1 class="title tc">RESERVE YOUR TABLE NOW</h1><hr />';
						htmlContent += '<form class="reservForm">';
						htmlContent += '<div class="row">';
						htmlContent +='<div class="col-md-12">';
						htmlContent += '<div class="form-group"><label>Party Size:</label>';
						htmlContent += '<select id="reservPax" name="reservPax" class="form-control">'
						for(var i = 1; i <= 20; i++){
							htmlContent += '<option>'+i+'</option>';
						}
						htmlContent += '</select></div></div>';
						htmlContent += '<div class="col-md-12">';
						htmlContent += '<div class="form-group"><label>Date:</label>';
						htmlContent += '<div class="input-group date"><input type="text" data-provide="datepicker" id="reservDate" class="form-control"><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div></div>';
						htmlContent += '<div class="dnone"><input type="hidden" id="reservResid" name="reservResid" value="'+resid+'"/><input type="hiddden" id="reservAction" name="reservAction" value="search"/></div>'
						htmlContent += '</div>';
						htmlContent += '<div class="gap"></div>';
						htmlContent += '<div class="row"><div class="gap"></div><div class="col-md-12"><a class="btn btn-default" id="reservSubmit" attr="nosource" style="width:100%; ">Reserve Now</a></div></div></form>';

						//htmlContent += '<div class="form-group"><label>Date:</label>';
						//htmlContent += '<input type="text" placeholder="Date" maxlength="40" class="inp1 date" value="" id="reservDate" name="reservDate"></div>';
						
						
						/*for(var it in mainListData.data){
							if(mainListData.data[it].id == resid){
								htmlContent += '<div class="form-group"><label>Type:</label>';
								var diningType = mainListData.data[it].item_specific.dining_type;
								htmlContent += '<select id="reservDiningType" class="form-control" style="text-transform:capitalize">';
								for(var item in diningType){
									if(diningType[item]){
										htmlContent += '<option attr="' +item+ '" >'+item+'</item>';
									}else{
										htmlContent += '<option disabled="disabled" attr="' +item+ '" >'+item+'</item>';
									}						
								}
								htmlContent += '</select>';
							}
						}
						
						htmlContent += '</div></div>';*/
						
						
						htmlContent +='</div>';
						htmlContent +='<div class="modal-close"><img src="/images/close.png"></div>';
						htmlContent +='</div>';
						htmlContent +='</div>';
						htmlContent +='</div>';
								htmlContent +='</div>';
						htmlContent +='</div>';
						$('body').append(htmlContent);

						var _rtl = false;
					    drawOwlCarousel(_rtl);

					    // Render Rating stars

					    rating('.modal-window');

					    // Remove modal element form DOM

					    $('.modal-window .modal-background, .modal-close').live('click',  function(e){
					        $('.modal-window').addClass('fade_out');
					        setTimeout(function() {
					            $('.modal-window').remove();
					        }, 300);
					    });
					}
				}else{
			    	Login();
			    }
			});
		$('#reservDate').live('change', function(){
	        $('.datepicker').hide();
	    });

		$('#reservSubmit').live('click',function(){
			var divRef = $('.reservModal');
			$('.reservError,.resConfirm,.reservSlots').remove();
			if($('#reservDate').val()){
				
				if($(this).attr('attr') == 'source'){
					var url = "http://www.dinedesk.com/Associate/Associate/partnersapi/key/53832ab7a845c/apiname/GA";
					url += '/restaurantid/'+resid;
					url += '/date/'+$('#reservDate').val();
					url += '/mealtype/'+$('#reservDiningType').val();
					url += '/partysize/'+$('#reservPax').val();
					var resDiv = $('.item[data-id = "'+ $('#reservResid').val() +'"]');
					$.post(url,function(response){
						if(response['status'] == 'Y'){
							var slotResult = response['slots'];
							$('.reservSearch').hide();
							var htmlRes = '';
							htmlRes += '<div id="timeSlot" class="resTimes reservSlots">';
			     			htmlRes += '<h1 class="title tc">COMPLETE YOUR RESERVATION</h2><hr/>';
				 			htmlRes += '<h2 style="margin-bottom:0;"><i><img src="/images/icons/restaurants-bars/restaurants/restaurant.png" alt=""></i>'+$('.resListResName').text()+'</h2>';
				 			htmlRes += '<figure class="resListResLoc">'+$('.resListResLoc').text()+'</figure>';
				 			htmlRes += '<div class="clear"></div>';
			     			htmlRes += '<ul class="clearfix list-unstyled booking_dtl">';
			     			htmlRes += '<li>';
			     			htmlRes += '<span class="dblock bold mrgn_btm10">GUESTS</span>';
			     			htmlRes += '<span class="dblock">'+$('#reservPax').val()+' People </span>';
			     			htmlRes += '</li>';
			     			htmlRes += '<li>';
			     			htmlRes += '<span class="dblock bold  mrgn_btm10">DATE</span>';
			     			htmlRes += '<span class="dblock">'+$('#reservDate').val()+'</span>';
			     			htmlRes += '</li>';
			     			htmlRes += '<li>';
			     			htmlRes += '<span class="dblock bold mrgn_btm10">Type</span>';
			     			htmlRes += '<span class="dblock">'+$('#reservDiningType').val()+'</span>';
			     			htmlRes += '</li>';
			     			htmlRes += '<li><a id="reservChange"><button type="button" class="btn btn-default dflt_btn_big pull-right" aria-expanded="false">Change</button></a></li>';
			     			htmlRes += '</ul>';
							htmlRes +='<div class="reservSlotsDiv"><ul class="dtp-results-times list-left reservTimeSlots">';
							for(var item in slotResult){
								htmlRes += '<li><a class="dtp-button ">'+slotResult[item]+'</a></li>'
							}
							htmlRes += '</ul>';
							htmlRes +='<div class="row clear">';
			      			htmlRes +='<div class="gap"></div>';
			      			htmlRes +='<div class="gap"></div>';
			      			htmlRes +='<div class="gap"></div>';
			      			htmlRes +='<div class="col-md-4"></div>';
			      			htmlRes +='<div class="col-md-4">';
			       			htmlRes +='<a id="reservConfirm" class="btn btn-default" >Confirm Reservation</a>';
			      			htmlRes +='</div>';
			      			htmlRes +='<div class="col-md-4"></div>';
			     			htmlRes +='</div></div>';
			    			htmlRes +='</div>';
							divRef.append(htmlRes);
						}else{
							$('.reservError').remove();
							divRef.append('<div class="reservError">'+response['message']+'</div>')
						}
					});
				}else{
					var htmlRes = '';
					htmlRes +='<div class="resConfirm">';
					htmlRes +='<div class="row">';
			     	htmlRes +='<div class="col-lg-12 col-md-12 col-sm-12">';
			      	htmlRes +='<h2 style="margin-bottom: 6px;">User Details</h2>';
	      	htmlRes +='<div class="col-md-6" style="padding:0;">';
			      	htmlRes +='<div class="form-group">';
			        htmlRes +='<label for="usr">First Name</label>';
			        htmlRes +='<input type="text" class="form-control" id="reservFname" name="reservFname">';
			      	htmlRes +='</div>';
			      	htmlRes +='<div class="form-group">';
			        htmlRes +='<label for="Email">Email</label>';
			        htmlRes +='<input type="email" class="form-control" id="reservEmail" name="reservEmail">';
			      	htmlRes +='</div>';
			      	htmlRes += '</div>';
			      	htmlRes +='<div class="col-md-6" style="padding-right:0;">';
			      	htmlRes +='<div class="form-group">';
			        htmlRes +='<label for="usr">Last Name</label>';
			        htmlRes +='<input type="text" class="form-control" id="reservLname" name="reservLname">';
			      	htmlRes +='</div>';	      	
			      	htmlRes +='<div class="form-group">';
			        htmlRes +='<label for="phone">Phone Number</label>';
			        htmlRes +='<input type="email" class="form-control" id="reservPhone" name="reservPhone">';
			      	htmlRes +='</div>';
			      	htmlRes += '</div>';
			      	htmlRes +='<div class="clearfix mrgn_top20">';
			       	htmlRes +='<button type="submit" class="btn btn-default dflt_btn_big" id="reservInitiate" attr="nosource">Reserve Now</button>';
			      	htmlRes +='</div>';
			     	htmlRes +='</div>';
			    	htmlRes +='</div>';
			    	htmlRes +='</div>';
			    	divRef.append(htmlRes);
				}
			}else{
				$('.reservError').remove();
				divRef.append('<div class="reservError">Please select date</div>')
			}

		});

		$('#reservChange').live('click',function(){
			$('.reservError,.resConfirm,.reservSlots').remove();
			$('.reservSearch').show();
		});

		$('.reservTimeSlots li a').live('click',function(){
			$('.reservTimeSlots li a').removeClass('reservSel');
			$(this).addClass('reservSel');
		});

		$('#reservConfirm').live('click',function(){
			var divRef = $('.reservModal');
			if($('.reservTimeSlots li a').hasClass('reservSel')){
				
				$('.reservSlotsDiv').hide();
				$('.reservError,.resConfirm').remove();
				var htmlRes = '';
				htmlRes +='<div class="resConfirm">';
				htmlRes +='<div class="row">';
		     	htmlRes +='<div class="col-lg-12 col-md-12 col-sm-12">';
		      	htmlRes +='<h2 style="margin-bottom: 6px;">User Details</h2>';
	      	htmlRes +='<div class="col-md-4" style="padding:0;">';
		      	htmlRes +='<div class="form-group">';
		        htmlRes +='<label for="usr">First Name</label>';
		        htmlRes +='<input type="text" class="form-control" id="reservFname" name="reservFname">';
		      	htmlRes +='</div>';
		      	htmlRes +='<div class="form-group">';
		        htmlRes +='<label for="Email">Email</label>';
		        htmlRes +='<input type="email" class="form-control" id="reservEmail" name="reservEmail">';
		      	htmlRes +='</div>';
		      	htmlRes += '</div>';
		      	htmlRes +='<div class="col-md-4" style="padding-right:0;">';
		      	htmlRes +='<div class="form-group">';
		        htmlRes +='<label for="usr">Last Name</label>';
		        htmlRes +='<input type="text" class="form-control" id="reservLname" name="reservLname">';
		      	htmlRes +='</div>';	      	
		      	htmlRes +='<div class="form-group">';
		        htmlRes +='<label for="phone">Phone Number</label>';
		        htmlRes +='<input type="email" class="form-control" id="reservPhone" name="reservPhone">';
		      	htmlRes +='</div>';
		      	htmlRes += '</div>';
		      	htmlRes +='<div class="clearfix mrgn_top20">';
		       	htmlRes +='<button type="submit" class="btn btn-default dflt_btn_big" id="reservInitiate" attr="source">Reserve Now</button>';
		      	htmlRes +='</div>';
		     	htmlRes +='</div>';
		    	htmlRes +='</div>';
		    	htmlRes +='</div>';
		    	divRef.append(htmlRes);
			}else{
				$('.reservError').remove();
				divRef.append('<div class="reservError">Please select a time slot to continue.</div>')
			}
		});

		$('#reservInitiate').live('click',function(){
			var divRef = $('.reservModal');
			if(!$('#reservFname').val() && !$('#reservFname').val()){
				$('.reservError').remove();
				divRef.append('<div class="reservError">Please add the details to confirm reservation.</div>')
				return false;
			}
			if($(this).attr('attr') == 'source'){
				var url = "http://www.dinedesk.com/Associate/Associate/partnersapi/key/53832ab7a845c/apiname/MR";
				url += '/restaurantid/'+resid;
				var selDate = $('#reservDate').val().split('-');
			      var monArr = {'Jan':1,'Feb':2,'Mar':3,'Apr':4,'May':5,'Jun':6,'Jul':7,'Aug':8,'Sep':9,'Oct':10,'Nov':11,'Dec':12};
			      url += '/date/'+monArr[selDate[1]]+'-'+selDate[0]+'-'+selDate[2];
				url += '/time/'+$('.reservSel').text();
				url += '/partysize/'+$('#reservPax').val();
				url += '/fname/'+$('#reservFname').val();
				url += '/lname/'+$('#reservLname').val()
				url += '/splrequest/';
				url += '/email/'+$('#reservEmail').val();
				url += '/phone/'+$('#reservPhone').val();
				url += '/mealtype/'+$('#reservDiningType').val();
				$.post(url,function(response){
					if(response['status'] == 'Y'){
						var bokid = response['message'];
						url = "<?= $this->url(array('module'=>'Restaurant','controller'=>'Restaurant','action'=>'saveapireservation'),'default',true);?>";
						url += '/restaurantid/'+resid;
						url += '/date/'+$('#reservDate').val();
						url += '/time/'+$('.reservSel').text();
						url += '/partysize/'+$('#reservPax').val();
						url += '/fname/'+$('#reservFname').val();
						url += '/lname/'+$('#reservLname').val()
						url += '/splrequest/';
						url += '/email/'+$('#reservEmail').val();
						url += '/phone/'+$('#reservPhone').val();
						url += '/mealtype/'+$('#reservDiningType').val();
						url += '/bokid/'+bokid;
						$.post(url,function(resp){
							alert('Reservation Confirmed')
							$('.modal-window').remove();
						});
					}
				});
			}else{
				url = "<?= $this->url(array('module'=>'Restaurant','controller'=>'Restaurant','action'=>'saveapireservation'),'default',true);?>";
				url += '/restaurantid/'+resid;
				url += '/date/'+$('#reservDate').val();
				url += '/partysize/'+$('#reservPax').val();
				url += '/fname/'+$('#reservFname').val();
				url += '/lname/'+$('#reservLname').val()
				url += '/splrequest/';
				url += '/email/'+$('#reservEmail').val();
				url += '/phone/'+$('#reservPhone').val();
				$.post(url,function(resp){
					alert('Reservation Confirmed')
					$('.modal-window').remove();
				});
			}
		});

		});
	function Login()
	{
     var htmlDia = '<div class="modal-window fade_in" style="z-index:5052;"><div class="modal-wrapper">';
        htmlDia += '<div class="modal-body" style="width:600px;"><div class="modal-content">';
        htmlDia +='<div class="login-container">';
        htmlDia +='<div class="col-md-11 login-content1">';
        htmlDia +='<header class="login-header">';
        htmlDia +='<h1 class="page-title" style="background:black;">Log In To ReserveDine</h1>';
        htmlDia +='</header>';
        htmlDia +='<div class="wrap">';
        htmlDia +='<div class="login-split-left">';
        htmlDia +='<form role="form" id="form-sign-in-account" >';
        //htmlDia +='<div class="">';
        htmlDia +='<div class="form-group">';
        htmlDia +='<label for="form-sign-in-email">Email:</label>';
        htmlDia +='<input type="email" class="form-control" id="form-sign-in-email"  name="emailAddress" required>';
        htmlDia +='</div>';
        htmlDia +='<div class="form-group" style="margin-top:10px;">';
        htmlDia +='<label for="form-sign-in-password">Password:</label>';
        htmlDia +='<input type="password" class="form-control" id="form-sign-in-password" name="password" required>';
        htmlDia +='</div>';
         htmlDia +='<div class="form-group loginerror" style="color:red;">';
        htmlDia +='</div>';
        htmlDia +='<div class="form-group clearfix" style="margin-top:10px;">';
        htmlDia +='<button type="submit" class="btn btn-default" id="account-submit">Log In</button>';
        htmlDia +='</div>';
        htmlDia +='<div class="form-group clearfix " style="margin-top:10px;">';
        htmlDia +='<a href="#" class="signUp">New User? Please Signup</a>';
        htmlDia +='</div>';
        htmlDia +='</form>';
        htmlDia +='</div>';
        htmlDia +='<ul class="login-split-right social-options">';
        htmlDia +='<h2>Connect with</h2>';
        htmlDia +='<li class="facebook">';
        htmlDia +='<button class="btn btn-default ng-isolate-scope ng-scope" login="" service="facebook"><i class="fa fa-facebook"></i></span> <span class="text" aria-hidden="Facebook">Facebook</span></button>';
        htmlDia +='</li>';
        htmlDia +='<li class="google">';
        htmlDia +='<div  login="" id="popup-Signin" service="google"><i class="fa fa-google-plus"></i> <span class="text" aria-hidden="Google">Google</span></div>';
        htmlDia +='</li>';
        htmlDia +='</ul><div class="clear"></div><div class="clear"></div>';
        htmlDia +='</div><div class="clear"></div>';
        htmlDia +='</div><div class="clear"></div>';
         htmlDia +='<div class="col-md-11 login-content2 dnone">';
        htmlDia +='<header class="login-header">';
        htmlDia +='<h1 class="page-title" style="background:black;">Signup To Rdine</h1>';
        htmlDia +='</header><br>';
      htmlDia += '<form  role="form"  action="" class="signUpForm" method="post">';
      htmlDia += '<div class="col-md-6 col-sm-6">';
      htmlDia += '<div class="form-group">';
      htmlDia += '<label for="name">Name</label>           ';
      htmlDia += '<input type="text" name="firstName" id="firstName" value="" class="inp1" maxlength="30" title="First Name" placeholder="First Name*"></div>';
      htmlDia += '</div>';
      htmlDia += '<div class="col-md-6 col-sm-6">';
      htmlDia += '<div class="form-group">';
      htmlDia += '<label for="Last Name">Last Name</label>       ';
      htmlDia += '<input type="text" name="lastName" id="lastName" value="" maxlength="30" title="Last Name" placeholder="Last Name" class="inp1">';   
      htmlDia += '</div>';
      htmlDia += '</div>';
      htmlDia += '<div class="col-md-6 col-sm-6">';
      htmlDia += '<div class="form-group">';
      htmlDia += '<label for="email">Email Address</label>';
      htmlDia += '<input type="text" name="emailAddress" id="emailAddress" value="" class="inp1" maxlength="40" title="Email Address" placeholder="Email Address*"><span class="ajaxReturn"></span></div>';
      htmlDia += '</div>';
      htmlDia += '<div class="col-md-6 col-sm-6">';
      htmlDia += '<div class="form-group">';
      htmlDia += '<label for="password">Password</label>';
      htmlDia += '<input type="password" name="password" id="password" value="" class="inp1" maxlength="20" title="Password" placeholder="Password*"><img htmlDia += class="psdImg dNone">';
      htmlDia += '</div>';
      htmlDia += '</div>';
      htmlDia += '<div class="col-md-6 col-sm-6">';
      htmlDia += '<div class="form-group">';
      htmlDia += '<label for="password">Confirm Password</label>             ';
      htmlDia += '<input type="password" name="password_confirm" id="password_confirm" value="" class="inp1" maxlength="20" title="Confirm Password" placeholder="Confirm Password*"><img class="psdCnfImg dNOne">';
      htmlDia += '</div>';
       htmlDia += '<div class="form-group passwordError" style="color:red;">';
      htmlDia += '</div>';
      htmlDia += '</div>';
      htmlDia += '<div class="clear"></div><section>';
      htmlDia += '<div class="form-group">';
      htmlDia += '<button id="submit" class="btn btn-default pull-right" type="submit">Submit</button>';
      htmlDia += '</div>';
      htmlDia += '</form>';
       htmlDia +='<a href="#" class="signIn">Already User? Please Login</a>';
      htmlDia +='</div><div class="clear"></div>';
        htmlDia +='<div class="modal-close"><img src="/images/close.png"></div>';
        htmlDia +='</div>';       
        htmlDia += '</div></div></div><div class="modal-background fade_in"></div></div>';
        $('body').append(htmlDia);
        renderLoginButton();
    $("#form-sign-in-account").on('submit',function()
      {      
       var  SigninFormValues =new FormData($('#form-sign-in-account')[0]);              
        var url = "<?php echo $this->url(array('module'=>'User','controller'=>'Login','action'=>'signinajax'),'default',true);?>";
          $.ajax({
            url: url,   
            type: "POST", 
            data:SigninFormValues, 
            contentType: false,  
            cache: false,          
            processData:false,     
            success: function(data)
            {
              if(data==true)
              {
                
                $(".modal-close").click();
               location.reload();
              } 
              else
              {
                $(".loginerror").html("Invalid Login Please Try Again");
              }                       
            }
          });  
      return false; 
    });
    var emailValid = "";
    $('#submit').live('click',function(e){
      e.preventDefault();
         if($("#password").val()!=$("#password_confirm").val())
        {
          $(".passwordError").html("Password Didnt Match");
          return false;
        }
    emailObj.trigger('blur');
    var formData = $(".signUpForm").serializeArray();
    if(emailValid)
    {
      var url = "<?php echo $this->url(array('module'=>'User','controller'=>'Client','action'=>'guestwidgetsignup'),'default',true); ?>"
      $.post(url,formData,function(data)
      {
        if(data==true)
        {
             $(".modal-close").click();
               location.reload();
        }
      });
    }
    $(".signUpForm").submit();
    return emailValid;  
    });
    var emailObj = $("#emailAddress");
    emailObj.live('blur',function(){
  ajaxEmailCall();
   });
     $(".signUp").live('click',function()
    {
      $(this).parents('.login-content1').addClass("dnone");
      $(".login-content2").removeClass("dnone");
      return false;
    });
     $(".signIn").live('click',function()
     {
        $(this).parents('.login-content2').addClass("dnone");
      $(".login-content1").removeClass("dnone");
      return false;
     });
     function ajaxEmailCall(){
      var emailObj = $("#emailAddress");
    errorObj = $(".ajaxReturn");
   var url = "<?php echo $this->url(array('module'=>'User','controller'=>'Client','action'=>'searchforemailexist'),'default',true); ?>"
     errorObj.text(" ");
     var bValid = true;
     bValid = bValid && checkRegexp(emailObj,/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/,"<?php echo $this->translate->_('Invalid Email'); ?>");  
    function checkRegexp(o,regexp) {
      var emailObj = $("#emailAddress");
      if ( !( regexp.test( o.val() ) ) ) {  
        errorObj.text("<?php echo $this->translate->_('Invalid Email'); ?>");
        errorObj.css({'color':'#ED0E19'});
          emailValid = false;
          return false
      } else{
        return true;
      }
    }
    if(!bValid){
      return false;
    }
   $.post(url, { email: $.trim(emailObj.val()) },
         function(data){
          data = data.replace(/\s/g,"");
          if(data=="t"){
            errorObj.text("<?php echo $this->translate->_('Email Address is not available'); ?>");
            errorObj.css({'color':'#ED0E19'});
            emailValid = false;
          }else if(data == "f"){
            errorObj.text("<?php echo $this->translate->_('Email Address is available continue  registering'); ?>");
            errorObj.css({'color':'#0EED12'});
            emailValid = true;
          }
        });
  }

  }
		
	function getFiltersJson () 
	{
		var url = "<?php echo $this->url(array('module'=>'Restaurant','controller'=>'Restaurant','action'=>'getfiltersjson'),'default',true); ?>";
		 url += '/searchLocation/'+"<?= $this->searchLocation?>";
		var placeId = "<?php echo $this->searchLocation; ?>";
		$.post(url,{placeId:placeId},function(data)
		{
			data = JSON.parse(data);
			data = data['data'];
			for(var i in data)
			{
				for(var j in data[i])
				{
						var option = "<option value='"+data[i][j]['key']+"'>"+data[i][j]['value']+"</option>";
						$("select[name='"+i+"']").append(option).selectpicker('refresh');
				}			
			}
		});
	}
	function setFilterData(filterValues)
	{
		var filterData = new Array('data');
				filterData['data'] = new Array();
				var jsonData = onloadjsondata['data'];
	-			$(jsonData).each(function()
				{ 	
					var item_specific = $(this)[0]['item_specific'];
					var matched = 0;
					var total = 0;
					for(var i in filterValues)
					{
						if((filterValues[i].length>0)||(i=="others"))
						{
							if(i!="others")
							{
								total++;	
							}

							switch(i)
							{
								case  "costfor2" :
									var val = parseInt(item_specific["pricefor2"]);
									var key = filterValues["costfor2"];
									key = key.split("-");

									for(var k in key)
									{
										key[k] = key[k].replace(/\s/g, "");
										key[k] = parseInt(key[k]);
									}
									if((key[0]<=val)&&(key[1]>=val))
									{
										matched++;
									}
								break;
								case "cusine" :
								var val = item_specific[i];
								var key = filterValues[i];
								key = key.replace(/\s/g, "");
								if(val.length>0)
								{
									for(var c in val)
									{
										val[c] = val[c].replace(/\s/g, "");
										if(key==val[c])
										{							
											matched++;
										}
									}
								}
								break;
								case 'others':
								for(var o in filterValues[i])
								{
									for(var c in filterValues[i][o])
									{
										total++;
										var val = item_specific[o][c];
										val = val.toString(/\s/g, "");
										val = val.replace()
										var key = filterValues[i][o][c];
										key = key.replace(/\s/g, "");		
										if(key==val)
										{			
											matched++;
										}
									}
								}
								break;
								default:
									var val = item_specific[i].toString();
									val = val.replace(/\s/g, "");
									var key = filterValues[i];
									key = key.replace(/\s/g, "");
									if(key==val)
									{						
										matched++;
									}
								break;
							}
						}
					}
					if(matched==total)
					{
						filterData['data'].push($(this)[0]);
					}
				});
				var popularityFilter = $("#popularity").val();
				if(popularityFilter!=="")
				{
					switch(popularityFilter)
					{
						case 'low':sortByKeyAsc(filterData['data'],"views");
						break;
						case 'high':sortByKeyDesc(filterData['data'],"views");
						break;
						case 'vhigh':sortByKeyAsc(filterData['data'],"visits");
						break;
						case 'excellent':sortByKeyDesc(filterData['data'],"visits");
						break;
					}
				}
				filterData['borderDetails'] = onloadjsondata.borderDetails;
				filterData['mapcenter'] = onloadjsondata.mapcenter;
				$(".resultsNumber").html(filterData.data.length);
				createHomepageGoogleMap(eval(filterData),null);
	}
	function getFilterValues()
	{
		var filterValues =  Array();
				$("select.filter").not("#popularity").each(function()
				{
					filterValues[$(this).attr("name")] = $(this).val();
				});
		filterValues['others'] = Array();
				$(".other-filter-selected").each(function()
				{
					var filterCategory = $(this).attr('data-filter-category');
					var typeVal = $(this).attr('data-filter');
					if(!filterValues['others'].hasOwnProperty(filterCategory))
					{
						filterValues['others'][filterCategory] = Array();
						filterValues['others'][filterCategory][typeVal] = "true";
					}
					else
					{
						filterValues['others'][filterCategory][typeVal] = "true";	
					}
				});
				if($(".openNow").attr("data-value")=="true")
				{
					filterValues['isOpen'] = $(".openNow").attr("data-value");
				}
		return filterValues;
	}
	
	function sortByKeyDesc(array, key) {
    return array.sort(function(a, b) {
        var x = a[key]; var y = b[key];
        return ((x < y) ? 1 : ((x > y) ? -1 : 0));
    });
	}
	function sortByKeyAsc(array, key) {
    return array.sort(function(a, b) {
        var x = a[key]; var y = b[key];
        return ((x < y) ? -1 : ((x > y) ? 1 : 0));
    });
	}
	function quickView(id){
    /*
    $.ajax({
        type: 'POST',
        url: '/external/_modal.html',
        data: id,
        success: function (data) {
            // Create HTML element with loaded data
            $('body').append(data);
        }
    });*/
	var tempdata = onloadjsondata.data;
	var jsondata ;
	var jsontimes ;
	for(var i in tempdata)
	{
	    if(id==tempdata[i]['id'])
	    {
	        jsondata = tempdata[i];
	    }
	}
	var reslikes = jsondata.item_specific.likes;
	if(reslikes==null)
	{
		reslikes = 0;
	}
	var resdislikes = jsondata.item_specific.dislikes;
	if(resdislikes==null)
	{
		resdislikes = 0;
	}
	var resreviews = jsondata.item_specific.reviews;
	if(resreviews==null)
	{
		resreviews = 0;
	}
	    htmlContent ='';
	htmlContent +='<div class="modal-window fade_in">';
	htmlContent +='<div class="modal-wrapper">';
	htmlContent +='<div class="modal-body">';
	htmlContent +='<div class="gallery">';
	htmlContent +='<div class="image">             ';
	htmlContent +='<div class="owl-carousel gallery">';
	var gallery = jsondata.gallery;
	for(var i in gallery)
	{
	    htmlContent +='<img src="'+gallery[i]+'">';
	}
	htmlContent +='</div>';
	htmlContent +='<div class="buttons item-review">';
	htmlContent +='<div class="row">';
	htmlContent +='<div class="col-md-8" style="padding-top: 3px;">';
	htmlContent +='<a href="#" class="pull-left white resliked" data-id="'+jsondata.id+'"><i class="fa fa-thumbs-up white"></i>'+reslikes+'</a>';
	htmlContent +='<a href="#" class="pull-left white resdisliked" data-id="'+jsondata.id+'"><i class="fa fa-thumbs-down white data-id="'+jsondata.id+'"></i>'+resdislikes+'</a> ';
	htmlContent +='<a href="#" class="pull-left white last"><i class="fa fa-heart white"></i>'+resreviews+ 'reviews</a> ';
	htmlContent +='<div class="rating-small pull-left margin-0">'+jsondata.rating+'</div>';
	htmlContent +='</div>';
	htmlContent +='<div class="col-md-4">                              ';
	htmlContent +='<div class="sml-btn1 pull-right green resReserv" attr="'+id+'">Reserve</div> ';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='</div> ';
	htmlContent +='</div>';
	htmlContent +='<div class="modal-content">     ';
	htmlContent +='<section>   ';
	htmlContent +='<div class="title3">';
	htmlContent +='<h1 style="margin-bottom:0;"><a class="resListResName" href="/'+jsondata.city_name.toLowerCase().replace(' ','_')+'/'+jsondata.vanityUrl+'" reslistedRestaurant="'+jsondata.restaurant_id+'">'+jsondata.title+'</a></h1>';
	htmlContent +='<figure class="resListResLoc">'+jsondata.location+'</figure>';
	htmlContent +='<p>'+jsondata.item_specific.cusine+'</p>';
	if(jsondata.item_specific.nonveg)
	{
	    htmlContent +='<p>Vegiterian</p>';
	}
	htmlContent += '<div class="type"><i><img src="/images/icons/restaurants-bars/restaurants/restaurant.png" alt=""></i> ';
	htmlContent += jsondata.item_specific.diningStyle+'</div>';
	htmlContent +='</div>  ';
	htmlContent +='</section>';
	htmlContent +='<section>';
	htmlContent +='<h3>Cost for 2  › <span>Rs. '+jsondata.item_specific.pricefor2+'</span></h3>';
	htmlContent +='<h3>Known For   ›';
	htmlContent += '<span> '+jsondata.item_specific.specialities+'</span></h3>';
	htmlContent +='<div class="row">';
	htmlContent +='<div class="col-md-12">';
	htmlContent +='<div class="pull-left">';
	var to = "/"+jsondata.city_name.toLowerCase().replace(' ','_')+"/"+jsondata.vanityUrl;
	htmlContent +='<a href="'+to+'#menu" class="sml-btn"><i class="fa fa-list green1"></i> Menu</a> ';
	htmlContent +='</div>';
	htmlContent +='<div class="pull-left">';
	htmlContent +='<a href="'+to+'#gallery" class="sml-btn"><i class="fa fa-image green1"></i> Photo</a> ';
	htmlContent +='</div>';
	htmlContent +='<div class="pull-left">';
	htmlContent +='<a href="'+to+'#reviews" class="sml-btn"><i class="fa fa-star green1"></i> Reviews</a> ';
	htmlContent +='</div>  ';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='</section>';
	htmlContent +='<section><h3>Opening Hours</h3>';
	htmlContent +='<figure>';
	htmlContent +='<div class="expandable-content collapsed show-30" id="detail-sidebar-event">';
	htmlContent +='<div class="content">';
	htmlContent +='<dl class="lines">';
	if(jsondata.timings.length !== 0)
	{
	    var temptimes = jsondata.timings;
	    for(var j in temptimes)
	    {
	        htmlContent +='<dt>'+j+'</dt>'; 
	        var temptype = temptimes[j];
	        for(var k in temptype)
	        {
	            htmlContent +='<dd>'+temptype[k]['rwt_sch_type']+' - '+temptype[k]['rwt_start_time']+'-'+temptype[k]['rwt_end_time']+'</dd>';
	        }
	    }
	   
	}
	else
	{
		htmlContent +='<dt>Sunday</dt>';
	    htmlContent +='<dd>No data found</dd>';
	     htmlContent +='<dt>Monday</dt>';
	    htmlContent +='<dd>No data found</dd>';
	    htmlContent +='<dt>Tuesday</dt>';
	    htmlContent +='<dd>No data found</dd>';
	    htmlContent +='<dt>Wednesday</dt>';
	    htmlContent +='<dd>No data found</dd>';
	    htmlContent +='<dt>Thursday</dt>';
	    htmlContent +='<dd>No data found</dd>';
	    htmlContent +='<dt>Friday</dt>';
	    htmlContent +='<dd>No data found</dd>';
	    htmlContent +='<dt>Saturday</dt>';
	    htmlContent +='<dd>No data found</dd>';
	}
	htmlContent +='</dl>                                                           ';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='<a href="#" class="show-more expand-content" data-expand="#detail-sidebar-event">Show More</a>';
	htmlContent +='</figure>';
	htmlContent +='</section>';
	htmlContent +='<section>';
	htmlContent +='<h3>Features</h3>';
	htmlContent +='<div class="view-all">';
	htmlContent +='<div class="row">';
	htmlContent +='<div class="col-md-6">';
	htmlContent +='<div class="filter-container">';
	htmlContent +='<span class="label title4">Seating Type</span>';
	htmlContent +='<div class="filter-btn-wrap">';
	htmlContent +='<ul class="list facilities-list">';
	if(jsondata.item_specific.seating_type.outdoor_seating == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-flexible"></i>Out Door Seating</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-flexible"></i>Out Door Seating</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	if(jsondata.item_specific.seating_type.ac == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-aircon"></i> Air Condition</div> <i class="fa fa-check pull-right"></i></li>'; 
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-aircon"></i> Air Condition</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	if(jsondata.item_specific.seating_type.delivery == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-departure"></i>Delivery</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-departure"></i>Delivery</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	
	if(jsondata.item_specific.seating_type.dine_in == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-breakfast"></i> Dine-In Available</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-breakfast"></i> Dine-In Available</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	if(jsondata.item_specific.seating_type.alcohol == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-winebar"></i>  Bar Available </div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-winebar"></i>  Bar Available </div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	htmlContent +='</ul>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='<div class="col-md-6">';
	htmlContent +='<div class="filter-container">';
	htmlContent +='<span class="label title4">Accepts</span>';
	htmlContent +='<div class="filter-btn-wrap">';
	htmlContent +='<ul class="list facilities-list">';
	if(jsondata.item_specific.payment_methods.cash == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-savings"></i>Cash</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-savings"></i>Cash</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	if(jsondata.item_specific.payment_methods.credit_card == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-card"></i>Credit Card</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-card"></i>Credit Card</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	if(jsondata.item_specific.payment_methods.gift_vouchers == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-card"></i>Gift Certificates </div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-card"></i>Gift Certificates </div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	if(jsondata.item_specific.payment_methods.visa_card == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-card"></i>Visa Card</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-card"></i>Visa Card</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	if(jsondata.item_specific.payment_methods.master_card == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-card"></i>Master card</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +=' <li><div class="icon-box style1"><i class="soap-icon-card"></i>Master card</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	htmlContent +='</ul>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='<div class="row">';
	htmlContent +='<div class="col-md-6">';
	htmlContent +='<div class="filter-container">';
	htmlContent +='<span class="label title4">Entertainment</span>';
	htmlContent +='<div class="filter-btn-wrap">';
	htmlContent += '<ul class="list facilities-list">';
	if(jsondata.item_specific.entertainment.wifi == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-wifi"></i>Free wifi</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-wifi"></i>Free wifi</div> <i class="fa fa-check pull-right"></i></li>';
	}
	if(jsondata.item_specific.entertainment.television == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-television"></i>Television</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-television"></i>Television</div> <i class="fa fa-check pull-right"></i></li>';
	}
	if(jsondata.item_specific.entertainment.sports_telecast == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-binoculars"></i>Sports telecast</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-binoculars"></i>Sports telecast</div> <i class="fa fa-check pull-right"></i></li>';
	}
	if(jsondata.item_specific.entertainment.live_music == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-triangle-right"></i>Live Music</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-triangle-right"></i>Live Music</div> <i class="fa fa-check pull-right"></i></li>';
	}
	htmlContent += '</ul>';
    htmlContent += '</div>';
    htmlContent += '</div>';
    htmlContent += '</div>';
    htmlContent += '<div class="col-md-6">';
	htmlContent +='<div class="filter-container">';
	htmlContent +='<span class="label title4">Dining Type</span>';
	htmlContent +='<div class="filter-btn-wrap">';
	htmlContent += '<ul class="list facilities-list">';
	if(jsondata.item_specific.dining_type.breakfast == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-food"></i>Breakfast</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-food"></i>Breakfast</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	
	if(jsondata.item_specific.dining_type.brunch == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-coffee"></i>Brunch</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-coffee"></i>Brunch</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	
	if(jsondata.item_specific.dining_type.lunch == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-breakfast"></i>Lunch</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-breakfast"></i>Lunch</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	
	if(jsondata.item_specific.dining_type.dinner == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-fireplace"></i>Dinner</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-fireplace"></i>Dinner</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	htmlContent +='</ul>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='<div class="row">';
	htmlContent +='<div class="col-md-6">';
	htmlContent +='<div class="filter-container">';
	htmlContent +='<span class="label title4">Buffet</span>';
	htmlContent +='<div class="filter-btn-wrap">';
	htmlContent += '<ul class="list facilities-list">';
	if(jsondata.item_specific.buffet.breakfast == true)
	{
	    htmlContent +=' <li><div class="icon-box style1"><i class="soap-icon-food"></i>Breakfast</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +=' <li><div class="icon-box style1"><i class="soap-icon-food"></i>Breakfast</div> <i class="fa fa-check pull-right"></i></li>';
	}
	if(jsondata.item_specific.buffet.lunch_buffet == true)
	{
	    htmlContent +=' <li><div class="icon-box style1"><i class="soap-icon-breakfast"></i>Lunch</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +=' <li><div class="icon-box style1"><i class="soap-icon-breakfast"></i>Lunch</div> <i class="fa fa-check pull-right"></i></li>';
	}
	if(jsondata.item_specific.buffet.dinner_buffet == true)
	{
	    htmlContent +=' <li><div class="icon-box style1"><i class="soap-icon-fireplace"></i>Dinner</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +=' <li><div class="icon-box style1"><i class="soap-icon-fireplace"></i>Dinner</div> <i class="fa fa-check pull-right"></i></li>';
	}
	htmlContent += '</ul>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent += '<div class="col-md-6">';
	htmlContent +='<div class="filter-container">';
	htmlContent +='<span class="label title4">Parking</span>';
	htmlContent +='<div class="filter-btn-wrap">';
	htmlContent += '<ul class="list facilities-list">';
	if(jsondata.item_specific.parking.parking_valet == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-parking"></i>Valet Parking</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-parking"></i>Valet Parking</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	if(jsondata.item_specific.parking.parking_prepaid == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-card"></i>Prepaid</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-card"></i>Prepaid</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	if(jsondata.item_specific.parking.parking_public == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-globe"></i>Public</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-globe"></i>Public</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	htmlContent +='</ul>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='<div class="row">';
	htmlContent += '<div class="col-md-6">';
	htmlContent +='<div class="filter-container">';
	htmlContent +='<span class="label title4">Special</span>';
	htmlContent +='<div class="filter-btn-wrap">';
	htmlContent += '<ul class="list facilities-list">';
	if(jsondata.item_specific.special.romantic_setup == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-fridge"></i>Romantic setup</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-fridge"></i>Romantic setup</div> <i class="fa fa-check pull-right"></i></li>';
	}
	if(jsondata.item_specific.special.special_ocassion_dining == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-fireplace"></i>Special Occasion</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-fireplace"></i>Special Occasion</div> <i class="fa fa-check pull-right"></i></li>';
	}
	htmlContent +='<ul>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='<div class="col-md-6">'; 
	htmlContent +='<div class="filter-container">';
	htmlContent +='<span class="label title4">Convenience</span>';
	htmlContent +='<div class="filter-btn-wrap">';
	htmlContent += '<ul class="list facilities-list">';
	if(jsondata.item_specific.convinience.kids_section == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-food"></i>Children Friendly</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-food"></i>Children Friendly</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	
	if(jsondata.item_specific.convinience.wheelchair == true)
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-breakfast"></i>Wheel chair accessible</div> <i class="fa fa-check pull-right"></i></li>';
	}
	else
	{
	    htmlContent +='<li><div class="icon-box style1"><i class="soap-icon-breakfast"></i>Wheel chair accessible</div> <i class="fa fa fa-remove disabled pull-right"></i></li>';
	}
	htmlContent +='</ul>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='</div>';
	htmlContent +='</section>';
	var href = "/"+jsondata.city_name.toLowerCase().replace(' ','_')+"/"+jsondata.vanityUrl;
	htmlContent +='<a href="'+href+'" class="btn btn-default btn-large">Show Detail</a></div>';
	htmlContent +='</div>';
	htmlContent +='<div class="modal-close"><img src="/images/close.png"></div>';
	htmlContent +='</div>';
	htmlContent +='</div>';
  $('body').append(htmlContent);
  var _rtl = false;
    drawOwlCarousel(_rtl);

    // Render Rating stars

    rating('.modal-window');

    // Remove modal element form DOM

    $('.modal-window .modal-background, .modal-close').live('click',  function(e){
        $('.modal-window').addClass('fade_out');
        setTimeout(function() {
            $('.modal-window').remove();
        }, 300);
    });
  var url = "<?php echo $this->url(array('module'=>'Restaurant','controller'=>'Restaurant','action'=>'updateviewajax'),'default',true); ?>";
  $.post(url,{restaurant_id:id},function(data)
  {});
}
function showShortlist()
{
 var htmlLike = "";
var loggedin = "<?php echo $this->isLoggedIn ?>" ;         
	 if(loggedin)
	 {
	 	var url = "<?php echo $this->url(array('module'=>'Restaurant','controller'=>'Restaurant','action'=>'shortlistfetch'),'default',true);?>"
		    	$.post(url,function(data)
				{
					data = JSON.parse(data);
					var htmlLike ="";			
					if(data.length==0)
					{
						 htmlLike+='<i class="fa fa-heart"></i><span class="summary">0</span><h2 class="text">Shortlist</h2>';
	     					  $(".shortlist-summary").html(htmlLike);
	     					    $(".items-list .results2").html("<li>Shortlist your favorite restaurants to find them quickly!!</li>");
					}
					else
					{
						 htmlLike+='<i class="fa fa-heart"></i><span class="summary">'+data.length+'</span><h2 class="text">Shortlist</h2>';
	     					  $(".shortlist-summary").html(htmlLike);
	     				drawList(data);
					}
				});
	 }
  else
  {
	  if((localStorage.getItem("shortlistDetails")==null)||(localStorage.getItem("shortlistDetails")=="[]"))
	      {
		     htmlLike+='<i class="fa fa-heart"></i> <span class="summary">0 </span><h2 class="text">Shortlist</h2>';
		     					  $(".shortlist-summary").html(htmlLike);
		     					    $(".items-list .results2").html("<li>Shortlist your favorite restaurants to find them quickly!!</li>");
		  }
		  else
		  {
		  	drawList(JSON.parse(localStorage['shortlistDetails']));
		  }
  }
    
}
function drawList(data)
{
   var likesData = Array();
   likesData = data;
    var htmlLike='<i class="fa fa-heart"></i> <span class="summary">'+likesData.length+'</span> <h2 class="text">Shortlist</h2>';
 					  $(".shortlist-summary").html(htmlLike);
   for(var i in likesData)
   {
   		if(likesData[i].hasOwnProperty('data'))
   		{

   			addLikeItem(likesData[i].data,"onload");
   		}
   		else
   		{
   			addLikeItem(likesData[i],"onload");
   		}
   }
}
function addLikeItem (likesData,called) 
{
	var currentlikes = parseInt($(".shortlist-summary > span").html());
	if(currentlikes==0)
	{
		 $(".items-list .results2").html("");
	}
	if(called=="onload")
	{	
		$(".shortlist-summary > span").html(currentlikes);
	}
	else
	{
		$(".shortlist-summary > span").html(currentlikes+1);
	}

	var toRes = '/'+likesData.city_name.toLowerCase()+'/'+likesData.vanityUrl;
	var htmlLike = "";
	htmlLike += '<li>' ;
	htmlLike += '<div class="item" data-id="' + likesData.id + '">' ;
	htmlLike += '<a href="'+toRes+'" class="image">' ;
	htmlLike += '<div class="inner">' ;
	htmlLike += '<div class="item-specific">' ;
	htmlLike += '</div>' ;
	htmlLike += '<img src="' + likesData.gallery[0] + '" alt="">' ;
	htmlLike += '<div style="position: absolute;right: 4px;top: 4px;"><i class="fa fa-heart red likeButton" data-score="1" style="font-size:24px;" data-id="'+likesData['id']+'"></i></div>';
	htmlLike += '</div>' ;
	htmlLike += '</a>' ;
	htmlLike += '<div class="wrapper">' ;
	htmlLike += '<a href="'+toRes+'" id="' + likesData.id + '"><h3 title="'+likesData.title+'">' + likesData.title.substr(0,20) + '</h3></a>' ;
	htmlLike += '<div style="position:absolute; top:4px; right:4px;" class="res-rating">'+likesData.rating+'</div>' ;
	htmlLike += '<figure>' + likesData.location + '</figure>' ;
	htmlLike += '<div class="info">' ;
	htmlLike += '<div class="type">' ;
	htmlLike += '<p><strong>Dining Type:</strong>' + likesData.item_specific.diningStyle + '</p>' ;
	htmlLike += '<p><strong>Cusine:</strong>'+likesData.item_specific.cusine.toString().substr(0,28)+'..</p>';
	htmlLike += '</div>' ;
	htmlLike += '</div>' ;
	htmlLike += '</div>' ;
	htmlLike += '</div>' ;
	htmlLike += '</li>';
	$(".results2").append(htmlLike);

}
function removeLikeItem(index)
{
	var currentlikes = parseInt($(".shortlist-summary > span").html());
	$(".shortlist-summary > span").html(currentlikes-1);
	$(".results2 > li > .item[data-id='"+index+"']").remove();	
	$("i[data-id='"+index+"']").removeClass("red");
	if((currentlikes-1)==0)
	{
	$(".items-list .results2").html("<li>Shortlist your favorite restaurants to find them quickly!!</li>");
	}
}
	</script>
	        <!-- Page Canvas-->
	        <div id="page-canvas">
	            <!--Off Canvas Navigation-->
	            <nav class="off-canvas-navigation">
	                <header>Navigation</header>
	                <div class="main-navigation navigation-off-canvas"></div>
	            </nav>
			
	            <div id="page-content">
				
				<div class="search-bar horizontal">
	                      <figure class="filter clearfix" style="box-shadow:0 1px 10px -3px rgba(0,0,0,.5); padding:6px; background:#fff;">
	                                
	                                <div class="buttons pull-left">
	                                    <aside class="sorting">
	                                        <div class="form-group" style="min-width:120px; margin-right:10px;">
	                                            <select class="framed filter" name="diningStyle">
	                                              
	                                            </select>
	                                        </div>
	                                        <!-- /.form-group -->
	                                    </aside>
	                                </div>
	                                <div class="buttons pull-left">
	                                    <aside class="sorting">
	                                        <div class="form-group" style="min-width:120px; margin-right:10px;">
	                                            <select class="framed filter"  name="cusine">
	                                           
	                                            </select>
	                                        </div>
	                                        <!-- /.form-group -->
	                                    </aside>
	                                </div>
	                                <div class="pull-left">
	                                    <aside class="sorting">
	                                        <div class="form-group" style="min-width:120px; margin-right:10px;">
	                                            <select class="framed filter" name="costfor2">
	                                            
	                                            </select>
	                                        </div>
	                                        <!-- /.form-group -->
	                                    </aside>
	                                </div>
	                                <div class="pull-left">
	                                    <aside class="sorting">
	                                        <div class="form-group" style="min-width:120px; margin-right:10px;">
	                                            <select class="framed filter" id="popularity" name="popularity">
	                                                <option value="">Popularity</option>
	                                                <option value="low">Low</option>
	                                                <option value="high">High</option>
	                                                <option value="vhigh">Very High</option>
	                                                <option value="excellent">Excellent</option>
	                                            </select>
	                                        </div>
	                                        <!-- /.form-group -->
	                                    </aside>
	                                </div>
	                                <div class="pull-left">
	                                    <aside class="sorting">
	                                        <div class="form-group" style="min-width:120px; margin-right:10px;">
	                                            <select name = "nonveg" class="framed filter" name="type">
	                                                <option value="">Veg/Non-veg</option>
	                                                <option  value="false">Veg</option>
	                                                <option value="true">Non Veg</option>
	                                            </select>
	                                        </div>
	                                        <!-- /.form-group -->
	                                    </aside>
	                                </div>
	                                <div class="pull-left">
	                                    <aside class="sorting">
	                                        <div class="form-group" style="min-width:120px; margin-right:10px;">
	                                           <div class="btn-group bootstrap-select framed">
													<button type="button" class="btn dropdown-toggle selectpicker btn-default" data-toggle="dropdown" title="Others">
														<span class="filter-option pull-left">Others</span>&nbsp;<span class="caret"></span>
													</button>
													<ul class="dropdown-menu main more-filters-dropdown-menu" style="padding-left: 10px !important;">
														<div class="more-filters-dropdown-wrapper">
														<form class="clearfix more-filters" style="padding-bottom:20px;">
														<div class="">
															<div class="filter-container">
																<span class="label">Seating Type</span>
																<div class="filter-btn-wrap">
																	<div class="filter-btn" data-filter="outdoor_seating" data-filter-category="seating_type">Out Door Seating</div>
																	<div class="filter-btn" data-filter-category="seating_type" data-filter="ac"> Air Conditioned</div>
																	<div data-filter-category="seating_type" class="filter-btn" data-filter="delivery">Deliveries</div>
																	<div class="filter-btn" data-filter-category="seating_type" data-filter="dine_in">Dine In facility</div>
																	<div class="filter-btn" data-filter="alcohol" data-filter-category="seating_type">Bar Available</div>
																</div>
															</div>
															<div class="filter-container">
																<span class="label">Accepts</span>
																<div class="filter-btn-wrap">
																	<div class="filter-btn" data-filter-category="payment_methods" data-filter="cash">Cash</div>
																	<div class="filter-btn" data-filter-category="payment_methods" data-filter="credit_card">Credit Card</div>
																	<div class="filter-btn" data-filter-category="payment_methods" data-filter="gift_vouchers">Gift Certificates</div>
																	<div class="filter-btn" data-filter-category="payment_methods" data-filter="master_card">Master card</div>
																	<div class="filter-btn" data-filter-category="payment_methods" data-filter="visa_card">Visa Card </div>
																</div>
															</div>
															<div class="filter-container">
																<span class="label">Dining Type</span>
																<div class="filter-btn-wrap">
																	<div class="filter-btn" data-filter-category="dining_type" data-filter="breakfast">Breakfast</div>
																	<div class="filter-btn" data-filter-category="dining_type" data-filter="lunch">Lunch</div>
																	<div class="filter-btn" data-filter-category="dining_type" data-filter="dinner">Dinner</div>
																	<div class="filter-btn" data-filter-category="dining_type" data-filter="brunch">Brunch</div>
																</div>                      
															</div>
															<div class="filter-container">
																<span class="label">Convenience</span>
																<div class="filter-btn-wrap">
																	<div class="filter-btn" data-filter-category="convinience" data-filter="kids_section">Children Friendly</div>
																	<div class="filter-btn" data-filter-category="convinience" data-filter="wheelchair">Wheel chair accessible</div>
																</div>
															</div>
															<div class="filter-container">
																<span class="label">Parking</span>
																<div class="filter-btn-wrap">
																	<div class="filter-btn" data-filter-category="parking" data-filter="parking_valet">Valet Parking</div>
																	<div class="filter-btn" data-filter-category="parking" data-filter="parking_prepaidprepaid">Prepaid</div>
																	<div class="filter-btn" data-filter-category="parking" data-filter="parking_public">Public</div>
																</div>
															</div>
															<div class="filter-container">
																<span class="label">Entertainment</span>
																<div class="filter-btn-wrap">
																	<div class="filter-btn" data-filter-category="entertainment" data-filter="wifi">Free wifi</div>
																	<div class="filter-btn" data-filter-category="entertainment" data-filter="television">Television</div>
																	<div class="filter-btn" data-filter-category="entertainment" data-filter="sports_telecast">Sports telecast</div>
																	<div class="filter-btn" data-filter-category="entertainment" data-filter="live_music">Live Music</div>
																</div>
															</div>
														</div>
														</form>
														<div class="clearfix footer-filter">
														<div class="footer-filter-lfloat pull-left"></div>
														<div class="footer-filter-rfloat pull-right">
														<div class="btn btn-default other-filter-submit">
														Done
														</div>
														</div>
														</div>
														</div>
														</ul>
												</div>
	                                        </div>
	                                        <!-- /.form-group -->
	                                    </aside>
	                                </div>
	                                 <div class="pull-left">
	                                    <aside class="sorting">
	                                      <!--  <div class="form-group" style="min-width:120px; margin-right:10px;">
	                                            <select name = "isOpen" class="framed filter" name="type">
	                                                <option value="false">Open/Closed</option>
	                                                <option value="true">Open now</option>
	                                            </select>
	                                        </div>-->
	                                          <div class="form-group openNow" style="min-width:120px; margin-right:10px; padding-top:10px;" data-value="false">
                                           <a href="#"><i class="fa fa-eye"></i> Open Now</a>
                                        </div>
	                                        <!-- /.form-group -->
	                                    </aside>
	                                </div>
									<div class="btn-group grid-controls pull-right">
										<?php
										$listview = "/$this->searchCity";
										$mapview = "/$this->searchCity";
										if($this->searchOrder)
										{
											$listview .="/$this->searchOrder-$this->searchLocationName-restaurant";
											$mapview .="/$this->searchOrder-$this->searchLocationName-restaurant-map";
										}
										else
										{
											$listview .="/$this->searchLocationName-restaurant";
											$mapview .="/$this->searchLocationName-restaurant-map";
										}
										if($this->searchCriteria!=="")
										{
											$listview .="/$this->searchCriteria";
											$mapview .="/$this->searchCriteria";
										}
										if($this->searchLocationName=="")
										{
											$mapview = "#";
										}
										echo '<a href="'.$mapview.'" class="btn1 highlight">Map View</a><a href="'.$listview.'" class="btn1">List View</a>';
								?>
									</div>
	                            </figure>
	                        <!-- /.main-search -->
				</div>
	            <!-- Map Canvas-->
	            <div class="map-canvas list-width-30">
	                <!-- Map -->
	                <div class="map">
	                    <div class="toggle-navigation">
	                        <div class="icon">
	                            <div class="line"></div>
	                            <div class="line"></div>
	                            <div class="line"></div>
	                        </div>
	                    </div>
	                    <!--/.toggle-navigation-->
	                    <div id="map" class="has-parallax"></div>
	                    <!--/#map-->
	                    
	                    <!-- /.search-bar -->
	                </div>
	                <!-- end Map -->
	                <!--Items List-->
	                <div class="items-list" style="padding-top:0;">
						<div class="list-header-tabs unselectable">
							<span class="result-summary selected tab">
							<i class="fa fa-list"></i>
							<span class="summary resultsNumber"></span>
							<h2 class="text">Results</h2>
							</span>
							<span class="shortlist-summary tab glow">
							<i class="fa fa-heart"></i>
							<span class="summary">0</span>
							<h2 class="text">Shortlist</h2>
							</span>
							</div>
	                    <div class="inner">
	                        <ul class="results list results1">
	                        </ul>
	                        <ul class="results list results2 dnone">
	                        </ul>
							
	                    </div>
	                    <!--results-->
	                </div>
	                <!--end Items List-->
	            </div>
	            <!-- end Map Canvas-->
	
	     
	            </div>
	            <!-- end Page Content-->
	        </div>
	        <!-- end Page Canvas-->
	       
	<script type="text/javascript" src="/js/maps.js"></script>
	<!--[if lte IE 9]>
	<script type="text/javascript" src="/js/ie-scripts.js"></script>
	<![endif]-->
	<script>
	function getPlacId(position)
	{
		var toSend = "<?php echo $this->url(array('module'=>'Restaurant','controller'=>'Restaurant','action'=>'listjson'),'default',true); ?>";
		toSend += '/searchCriteria/';
		$.post("https://maps.googleapis.com/maps/api/geocode/json?latlng="+position.coords.latitude+","+position.coords.longitude+"&key=AIzaSyBeJh-phIa5j8jZ02-eM24TCcZCpjSxExI",function(data)
			{
	          	getUrl(data); 
			});
	}
	function getUrl(data)
	{
		url += '/searchLocation/'+data[0]['place_id'];
	}
	    var onloadjsondata;
	    var searchLocation = "<?= $this->searchLocation?>";
	    var url = "";
	    if(searchLocation!=="near-me")
	    {
	    	 url = "<?php echo $this->url(array('module'=>'Restaurant','controller'=>'Restaurant','action'=>'listjson'),'default',true); ?>";
		    url += '/searchLocation/'+"<?= $this->searchLocation?>";
		    url +='/searchCityId/'+"<?= $this->searchCityId?>";
		    url+='/isMap/'+true;
			url += '/searchCriteria/'+"<?= $this->searchCriteria?>";
			url +='/searchOrder/'+"<?= $this->searchOrder?>";
	    }
	    else
	    {
	    	if (navigator.geolocation) {
	         navigator.geolocation.getCurrentPosition(getPlacId);
		    } else {
		       alert("Geolocation is not supported by this browser.");
		    }
	    }
		$(function()
		{
				$.post(url,function(data){

				    if(data != 'f'){
				    	onloadjsondata = data;
				    	$(".resultsNumber").html(data.data.length);
				    	createHomepageGoogleMap(eval(onloadjsondata),function(){showShortlist();});
					}
				},'json');
		});

	    $(window).load(function(){
			$(".result-summary").click(function(){
				$(this).addClass('selected');
				$(".shortlist-summary").removeClass('selected');
				$(".results1").removeClass('dnone');
				$(".shortlist").addClass('dnone');
				$(".results2").addClass('dnone');
			});
			$(".shortlist-summary").click(function(){
				$(this).addClass('selected');
				$(".result-summary").removeClass('selected');
				$(".shortlist").removeClass('dnone');
				$(".results2").removeClass('dnone');
				$(".results1").addClass('dnone');
			});
	    });
	    autoComplete();
	</script>
	<!--[if lte IE 9]>
	<script type="text/javascript" src="/js/ie-scripts.js"></script>
	<![endif]-->
	</body>
	</html>
