<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>TecKnowledge</title>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/bootstrap.css">
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.css" type="text/css">
     <link rel="stylesheet" href="/css/style.css" type="text/css">
	<script type="text/javascript" src="/js/jquery.js"></script>
	 <script type="text/javascript" src="/js/jquery-1.7.js"></script>
	<script type="text/javascript" src="/bootstrap/js/bootstrap.min.js"></script>
		<script>
</script>
</head>
<style>	
	.list{
		margin-top:12px;
		padding-left:0px;
		}
	.list li i{
		margin-right:10px;
		}
	.list li{
		list-style: none;
		line-height:24px;
		}
	form.main-search{width:780px;}
	.show-tick .dropdown-toggle{
		padding:8px;
		border-radius:3px 0 0 3px !important;
		background:#fff url(/images/location.png) no-repeat 8px 8px !important;
		padding-left: 30px !important;
		}
		.form-group1{
		margin-left:20px;
		width:120px !important
		}
	.form-group1 .show-tick .dropdown-toggle {
		padding: 8px;
		border-radius: 3px !important;
		background: none !important;
		padding-left: 0px !important;
		color: #fff;
	}
	.form-group1 .bootstrap-select .selectpicker .caret:after{
		color:#fff;
		}
	#location{
		padding:8px;
		background:#fff url(/images/search1.png) no-repeat 4px 8px;
		padding-left: 30px !important;
		}
	.search1{	
		border-radius:0 3px 3px 0;
		padding:8px;
	}
	form.main-search{
		padding: 2px 0 0 0;
		}
	.search-bar.horizontal .main-search .input-row{
		margin-bottom: 0px !important;
		}

	</style>
</style>
<body onunload="" class="map-fullscreen page-homepage navigation-off-canvas" id="page-top">
	<div id="outer-wrapper">
		<!-- Inner Wrapper -->
		<div id="inner-wrapper">			
			<?php include('adminheader.phtml'); ?>
			<div id="page-canvas">
				<!--Page Content-->
				<div id="page-content">
					<div class="navbar navbar-default" role="navigation">
						<div class="container">
							<div class="collapse navbar-collapse">
								<ul class="nav navbar-nav">
									<li>
										<a href="#" class="dropdown-toggle active" data-toggle="dropdown" ><strong>Module  Management</strong><b class="caret"></b></a>
										<ul class="dropdown-menu multi-level">
											<li><a href="<?php echo $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'firmregistration'),null,true);?>">L1</a></li>
											<li><a href="<?php echo $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'managerestaurant'),null,true);?>">L2</a></li>
										</ul>
									</li>
								</ul>
							</div>
						</div>
					</div>
					<?php echo $this->layout()->content ?>			
				</div>
			</div>
			<?php include('footer.phtml'); ?>
		</div>
	</div>
</body>
</html>
