<footer id="page-footer">
	<div class="inner">
		<div class="footer-top">
			<div class="container">
				<div class="row">							
					<div class="col-md-5 col-sm-5">
						<section>
							<p><br /><img src="/images/logo.png" /></p>
							<p>
							ReserveDine is a location based restaurant locator application. ReserveDine helps power business of restaurants by directing customers to their door steps. The unique algorithm assists guests in locating restaurants based on their liking for food, age, taste, season, choice, location etc. The fun to have app also offers discounts and offers to its guests.
							</p>
						</section>
					</div>
					<div class="col-md-2 col-sm-2">
						<!--New Items-->
						<section>
							<h2>COMPANY</h2>
							<ul class="list">
								<li><a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'about'),'about',true); ?>">About Us</a></li>
								<li><a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'careers'),'careers',true); ?>">Careers</a></li>
								<li><a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'contact'),'contact',true); ?>">Contact Us</a></li>
								<li><a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'faqs'),'faqs',true); ?>">Faqs</a></li>
								<li><a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'termsofservice'),'termsofservice',true); ?>">Terms & Conditions</a></li>
								<li><a href="<?php echo $this->url(array('module' =>'default','controller'=>'index','action'=>'privacy'),'privacy',true); ?>">Privacy Policy</a></li>
							</ul>
						</section>
						<!--end New Items-->
					</div>
					<div class="col-md-2 col-sm-2">
						<!--Recent Reviews-->
						<section>
							<h2>EXPLORE</h2>
							<ul class="list">
								<li><a href="http://dinedesk.com" target="_blank">For Restaurants</a></li>
								<li><a href="http://www.tdine.com/" target="_blank">Blog</a></li>
								<li><a href="#">Mobile Site</a></li>
								<li><a href="#">Android</a></li>
								<li><a href="#">iOS</a></li>
							</ul>
						</section>
						<!--end Recent Reviews-->
					</div>
					<div class="col-md-3 col-sm-3">
						<section>
							<h2>Follow Us</h2>
							<div class="social">
								<a href="#" target="_blank" class="social-button"><i class="fa fa-facebook"></i> Facebook</a><br />
								<a href="#" target="_blank" class="social-button"><i class="fa fa-twitter"></i> Twitter</a><br />
								<a href="#https://www.linkedin.com/company/rdine target="_blank" class="social-button"><i class="fa fa-linkedin"></i> Linledin</a><br />
								<a href="#" target="_blank" class="social-button"><i class="fa fa-youtube"></i> Youtube</a><br />
							</div>
						</section>
					</div>
					<!--/.col-md-4-->
				</div>
				<!--/.row-->
			</div>
			<!--/.container-->
		</div>
		<!--/.footer-top-->
		<div class="footer-bottom">
			<div class="container">
				<span class="left">(C) ReserveDine, All rights reserved</span>
				<span class="right">
					<a href="#page-top" class="to-top roll"><i class="fa fa-angle-up"></i></a>
				</span>
			</div>
		</div>
		<!--/.footer-bottom-->
	</div>
</footer>