<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>ReserveDine</title>
	<meta name="description" content="Hyderabad Restaurants - Menus, Photos, Ratings and Reviews Restaurants in Hyderabad. Find the Best Restaurants in Hyderabad on ReserveDine - Hyderabad Restaurants">
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/style.css">
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/jquery.typeahead.css">
	<link rel="stylesheet" href="/css/datepicker.css" type="text/css">
	<link href="/fonts/font-awesome.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.css" type="text/css">
    <link rel="stylesheet" href="/css/bootstrap-select.min.css" type="text/css">
    <link rel="stylesheet" href="/css/owl.carousel.css" type="text/css">
    <link rel="stylesheet" href="/css/jquery.nouislider.min.css" type="text/css">
    <link rel="stylesheet" href="/css/style.css" type="text/css">
    <link rel="stylesheet" href="/css/user.style.css" type="text/css">
    <link rel="stylesheet" href="/css/jquery.filer.css" type="text/css">
	<link rel="shortcut icon" href="/images/favlogo.png">
	<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery.js"></script>
	<script type="text/javascript" src="/js/jquery-2.1.0.min.js"></script>
	<script type="text/javascript" src="/js/kiwi-slider.js"></script>
	<script type="text/javascript" src="/js/before.load.js"></script>
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&amp;libraries=places"></script>
	<script type="text/javascript" src="/js/jquery-migrate-1.2.1.min.js"></script>
	<script type="text/javascript" src="/bootstrap/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="/js/smoothscroll.js"></script>
	<script type="text/javascript" src="/js/bootstrap-select.min.js"></script>
	<script type="text/javascript" src="/js/jquery.hotkeys.js"></script>
	<script type="text/javascript" src="/js/jquery.nouislider.all.min.js"></script>
	<script type="text/javascript" src="/js/jquery.mCustomScrollbar.concat.min.js"></script>
	<script type="text/javascript" src="/js/infobox.js"></script>
	<script type="text/javascript" src="/js/richmarker-compiled.js"></script>
	<script type="text/javascript" src="/js/markerclusterer.js"></script>
	<script type="text/javascript" src="/js/custom.js"></script>
	<script type="text/javascript" src="/js/maps.js"></script>
	<script src="/js/jquery.filer.min.js" type="text/javascript"></script>
		<script src="/js/jquery.typeahead.js" type="text/javascript"></script>
		
<script type="text/javascript" src="/js/bootstrap-datepicker.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-36940933-17', 'auto');
  ga('send', 'pageview');

</script>
</head>
<script>
    // Render Owl carousel gallery

    var _rtl = false;
    drawOwlCarousel(_rtl);

    // Render Rating stars

    rating('.modal-window');

    // Remove modal element form DOM

    $('.modal-window .modal-background, .modal-close').live('click',  function(e){
        $('.modal-window').addClass('fade_out');
        setTimeout(function() {
            $('.modal-window').remove();
        }, 300);
    });
    $('body').click(function(){
    	if($(this).attr('id') != 'searchLocation' || $(this).attr('id') != 'searchCriteria'){
    		if($('.typeahead-container').hasClass('result hint backdrop')){
    			$('.typeahead-container').removeClass('result hint backdrop');
    		}
    	}
    });
   
</script>
<style>	
	.list{
		margin-top:12px;
		padding-left:0px;
		}
	.list li i{
		margin-right:10px;
		}
	.list li{
		list-style: none;
		line-height:24px;
		}
	form.main-search{width:780px;}
	.show-tick .dropdown-toggle{
		padding:8px;
		border-radius:3px 0 0 3px !important;
		background:#fff url(/images/location.png) no-repeat 8px 8px !important;
		padding-left: 30px !important;
		}
		.form-group1{
		margin-left:20px;
		width:120px !important
		}
	.form-group1 .show-tick .dropdown-toggle {
		padding: 8px;
		border-radius: 3px !important;
		background: none !important;
		padding-left: 0px !important;
		color: #fff;
	}
	.form-group1 .bootstrap-select .selectpicker .caret:after{
		color:#fff;
		}
	#location{
		padding:8px;
		background:#fff url(/images/search1.png) no-repeat 4px 8px;
		padding-left: 30px !important;
		}
	.search1{	
		border-radius:0 3px 3px 0;
		padding:8px;
	}
	form.main-search{
		padding: 2px 0 0 0;
		}
	.search-bar.horizontal .main-search .input-row{
		margin-bottom: 0px !important;
		}
	button.selectpicker{
		border: none !important;
		box-shadow: none !important;
	}

	</style>
</style>
<body onunload="" class="map-fullscreen page-homepage navigation-off-canvas" id="page-top">
	<div id="outer-wrapper">
		<!-- Inner Wrapper -->
		<div id="inner-wrapper">			
			<?php include('header.phtml'); ?>
			<div id="page-canvas">
				<!--Off Canvas Navigation-->
				<nav class="off-canvas-navigation">
					<header>Navigation</header>
					<div class="main-navigation navigation-off-canvas">
						<ul>
							<li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'index'),'default',true);?>">Home</a></li>
							 <?php 
								$storage = new Zend_Auth_Storage_Session();
								$data = $storage->read();
								$inactUrl = '';
								if($data['Usertype'] == 'RSO'){
									$inactUrl = $this->url(array('module'=>'Restaurant','controller'=>'Restaurant','action'=>'firmregistration'),'default',true);
									echo '<li><a href="'.$inactUrl.'">Dashboard</a></li>';
								}else if($data['Usertype'] == 'ADM'){
									$inactUrl = $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'managerestaurant'),'default',true);
									echo '<li><a href="'.$inactUrl.'">Dashboard</a></li>';
								}else if($data['Usertype'] == 'CUS'){
									$inactUrl = $this->url(array('module'=>'User','controller'=>'Client','action'=>'dashboard'),'default',true);
									echo '<li><a href="'.$inactUrl.'">Dashboard</a></li>';
								}
							?>							
							<li><a href="#">About Us</a></li>
							<!---<li><a href="#sub-level-1" class="has-child" data-toggle="collapse" aria-expanded="false" aria-controls="sub-level-1">Pages</a>
								<div class="collapse" id="sub-level-1">
									<ul>
										<li><a href="404.html">404</a></li>
										<li><a href="#sub-level-2" class="has-child" data-toggle="collapse" aria-expanded="false" aria-controls="sub-level-2">Blog</a>
											<div class="collapse" id="sub-level-2">
												<ul>
													<li><a href="blog-listing.html">Blog Listing</a></li>
													<li><a href="blog-detail.html">Blog Detail</a></li>
												</ul>
											</div>
										</li>
										<li><a href="company-detail.html">Company Detail</a></li>
										<li><a href="facet-search.html">Facet Search</a></li>
										<li><a href="item-detail.html">Item Detail</a></li>
										<li><a href="faq.html">FAQ</a></li>
										<li><a href="pricing.html">Pricing</a></li>
										<li><a href="profile.html">Profile</a></li>
										<li><a href="my-items.html">My Items</a></li>
										<li><a href="rtl.html">RTL</a></li>
										<li><a href="terms-conditions.html">Terms & Conditions</a></li>
										<li><a href="left-sidebar.html">Left Sidebar</a></li>
										<li><a href="right-sidebar.html">Right Sidebar</a></li>
									</ul>
								</div>
							</li>-->
							<li><a href="#">Contact</a></li>
							<?php echo $this->loggedInAs();?>	
						</ul>

						<!--[if lte IE 9]>
						<script type="text/javascript" src="/js/ie-scripts.js"></script>
						<![endif]-->


						</div>
				</nav>
				<!--end Off Canvas Navigation-->
				<!--Page Content-->
				<div id="page-content">
					<?php echo $this->layout()->content ?>			
				</div>
			</div>
			<?php include('footer.phtml'); ?>
		</div>
	</div>
	<script type="text/javascript">
		function onSuccess(googleUser) 
		{
		  var userprofile = googleUser.getBasicProfile();
		  var url = "<?php echo $this->url(array('module'=>'User','controller'=>'Login','action'=>'signingmail'),'default',true); ?>";
		 $.post(url,{profile:userprofile},function(data)
		 {
		 	if(data==true)
		 	{
		 		location.reload();
		 	}
		 });
		 
		}
		function onFailure(error) {
     	 console.log(error);
    	}
	function renderLoginButton() {
      gapi.signin2.render('popup-Signin', {
        'scope': 'https://www.googleapis.com/auth/plus.login',
        'width': 200,
        'height': 40,
        'longtitle': false,
        'theme': 'dark',
        'onsuccess': onSuccess,
        'onfailure': onFailure
      });
  }

	</script>
	<script src="https://apis.google.com/js/platform.js?onload=renderButton" async defer></script>
	<meta name="google-signin-client_id" content="655248623186-n8vltpa27ac9i4mvu9kdlbbsol22ql5q.apps.googleusercontent.com">
</body>
</html>
