<!DOCTYPE html>

<html lang="en-US">
<head>
    <meta charset="UTF-8"/>
	<title>ReserveDine</title>
	<meta name="description" content="Hyderabad Restaurants - Menus, Photos, Ratings and Reviews Restaurants in Hyderabad. Find the Best Restaurants in Hyderabad on ReserveDine - Hyderabad Restaurants">	
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/fonts/font-awesome.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.css" type="text/css">
    <link rel="stylesheet" href="/css/bootstrap-select.min.css" type="text/css">
    <link rel="stylesheet" href="/css/owl.carousel.css" type="text/css">
    <link rel="stylesheet" href="/css/jquery.nouislider.min.css" type="text/css">
    <link rel="stylesheet" href="/css/colors/brown.css" type="text/css">
    <link rel="stylesheet" href="/css/user.style.css" type="text/css">
	<link href="/images/favlogo.png" type="image/png" rel="shortcut icon">
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/jquery.typeahead.css">
    <style>
	#outer-wrapper #page-canvas{background:none;}
	</style>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-36940933-17', 'auto');
  ga('send', 'pageview');

</script>
</head>

<body onunload="" class="map-fullscreen page-homepage navigation-off-canvas" id="page-top">
	<!-- Outer Wrapper-->
	<div id="outer-wrapper">
		<!-- Inner Wrapper -->
		<div id="inner-wrapper">			
			<?php include('homeheader.phtml'); ?>
			<div id="page-canvas">
				<!--Off Canvas Navigation-->
				<nav class="off-canvas-navigation">
					<header>Navigation</header>
					<div class="main-navigation navigation-off-canvas">
						<ul>
							<li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'index'),null,true);?>">Home</a></li>
							<?php 
								$storage = new Zend_Auth_Storage_Session();
								$data = $storage->read();
								$inactUrl = '';
								if($data['Usertype'] == 'RSO'){
									$inactUrl = $this->url(array('module'=>'Restaurant','controller'=>'Restaurant','action'=>'firmregistration'),'default',true);
									echo '<li><a href="'.$inactUrl.'">Dashboard</a></li>';
								}else if($data['Usertype'] == 'ADM'){
									$inactUrl = $this->url(array('module'=>'Administrator','controller'=>'Administrator','action'=>'managerestaurant'),'default',true);
									echo '<li><a href="'.$inactUrl.'">Dashboard</a></li>';
								}else if($data['Usertype'] == 'CUS'){
									$inactUrl = $this->url(array('module'=>'User','controller'=>'Client','action'=>'dashboard'),'default',true);
									echo '<li><a href="'.$inactUrl.'">Dashboard</a></li>';
								}
							?>	
							<li><a href="#">About Us</a></li>
							<li><a href="#">Contact</a></li>
							<?php echo $this->loggedInAs();?>
						</ul>

						<!--[if lte IE 9]>
						<script type="text/javascript" src="/js/ie-scripts.js"></script>
						<![endif]-->


						</div>
				</nav>
				<!--end Off Canvas Navigation-->
				<!--Page Content-->
				<div id="page-content">
					<?php echo $this->layout()->content ?>			
				</div>
			</div>
			<?php include('footer.phtml'); ?>
		</div>
	</div>
<script type="text/javascript" src="/js/jquery-2.1.0.min.js"></script>
<script type="text/javascript" src="/js/kiwi-slider.js"></script>
<script type="text/javascript" src="/js/before.load.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&amp;libraries=places"></script>
<script type="text/javascript" src="/js/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/js/smoothscroll.js"></script>
<script type="text/javascript" src="/js/bootstrap-select.min.js"></script>
<script type="text/javascript" src="/js/jquery.hotkeys.js"></script>
<script type="text/javascript" src="/js/jquery.nouislider.all.min.js"></script>
<script type="text/javascript" src="/js/custom.js"></script>
<script type="text/javascript" src="/js/maps.js"></script>
<script src="/js/jquery.typeahead.js" type="text/javascript"></script>

<script>
    $(window).load(function(){
        var rtl = false; // Use RTL
        $("#loading").fadeOut("slow");
        initializeOwl(rtl);
		$(".main-searchDiv").click(function(){
			$(".search-bar").removeClass('dnone');	
			$(".ttl2").addClass('dnone');
		})
		$('body').click(function(){
	    	if($(this).attr('id') != 'searchLocation' || $(this).attr('id') != 'searchCriteria'){
	    		if($('.typeahead-container').hasClass('result hint backdrop')){
	    			$('.typeahead-container').removeClass('result hint backdrop');
	    		}
	    	}
	    });
    });
$(document).ajaxStart(function(){
 		$("#loading").show();
 	});
 	$(document).ajaxComplete(function(){
 		$("#loading").hide();
 	});
    autoComplete();
    $(window).on('beforeunload',function()
 	{
 		$("#loading").show();
 	});
    
</script>
<script>
      new KiwiSlider('kiwi-slider1',{direction:'H'});
</script>
<!--[if lte IE 9]>
<script type="text/javascript" src="/js/ie-scripts.js"></script>
<![endif]-->
</body>
</html>