<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>ReserveDine</title>
	<meta name="description" content="Hyderabad Restaurants - Menus, Photos, Ratings and Reviews Restaurants in Hyderabad. Find the Best Restaurants in Hyderabad on ReserveDine - Hyderabad Restaurants">
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/style.css">
	
	<link href="/fonts/font-awesome.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.css" type="text/css">
    <link rel="stylesheet" href="/css/bootstrap-select.min.css" type="text/css">
    <link rel="stylesheet" href="/css/owl.carousel.css" type="text/css">
    <link rel="stylesheet" href="/css/jquery.nouislider.min.css" type="text/css">
    <link rel="stylesheet" href="/css/style.css" type="text/css">
    <link rel="stylesheet" href="/css/user.style.css" type="text/css">
	<link rel="shortcut icon" href="/images/favlogo.png">
	<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery.js"></script>
	<script type="text/javascript" src="/js/jquery-2.1.0.min.js"></script>
	<script type="text/javascript" src="/js/kiwi-slider.js"></script>
	<script type="text/javascript" src="/js/before.load.js"></script>
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&amp;libraries=places"></script>
	<script type="text/javascript" src="/js/jquery-migrate-1.2.1.min.js"></script>
	<script type="text/javascript" src="/bootstrap/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="/js/smoothscroll.js"></script>
	<script type="text/javascript" src="/js/bootstrap-select.min.js"></script>
	<script type="text/javascript" src="/js/jquery.hotkeys.js"></script>
	<script type="text/javascript" src="/js/jquery.nouislider.all.min.js"></script>
	<script type="text/javascript" src="/js/jquery.mCustomScrollbar.concat.min.js"></script>
	<script type="text/javascript" src="/js/infobox.js"></script>
	<script type="text/javascript" src="/js/richmarker-compiled.js"></script>
	<script type="text/javascript" src="/js/markerclusterer.js"></script>
	<script type="text/javascript" src="/js/custom.js"></script>
	<script type="text/javascript" src="/js/maps.js"></script>
	<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-36940933-17', 'auto');
  ga('send', 'pageview');

</script>
</head>
<script>
    // Render Owl carousel gallery

    var _rtl = false;
    drawOwlCarousel(_rtl);

    // Render Rating stars

    rating('.modal-window');

    // Remove modal element form DOM

    $('.modal-window .modal-background, .modal-close').live('click',  function(e){
        $('.modal-window').addClass('fade_out');
        setTimeout(function() {
            $('.modal-window').remove();
        }, 300);
    });
</script>
<style>	
	.list{
		margin-top:12px;
		padding-left:0px;
		}
	.list li i{
		margin-right:10px;
		}
	.list li{
		list-style: none;
		line-height:24px;
		}
	form.main-search{width:780px;}
	.show-tick .dropdown-toggle{
		padding:8px;
		border-radius:3px 0 0 3px !important;
		background:#fff url(/images/location.png) no-repeat 8px 8px !important;
		padding-left: 30px !important;
		}
		.form-group1{
		margin-left:20px;
		width:120px !important
		}
	.form-group1 .show-tick .dropdown-toggle {
		padding: 8px;
		border-radius: 3px !important;
		background: none !important;
		padding-left: 0px !important;
		color: #fff;
	}
	.form-group1 .bootstrap-select .selectpicker .caret:after{
		color:#fff;
		}
	#location{
		padding:8px;
		background:#fff url(/images/search1.png) no-repeat 4px 8px;
		padding-left: 30px !important;
		}
	.search1{	
		border-radius:0 3px 3px 0;
		padding:8px;
	}
	form.main-search{
		padding: 2px 0 0 0;
		}
	.search-bar.horizontal .main-search .input-row{
		margin-bottom: 0px !important;
		}

	</style>
</style>
<body onunload="" class="map-fullscreen page-homepage navigation-off-canvas" id="page-top">
	<div id="outer-wrapper">
		<!-- Inner Wrapper -->
		<div id="inner-wrapper">			
			<?php include('header.phtml'); ?>
			<div id="page-canvas">
				<!--Off Canvas Navigation-->
				<nav class="off-canvas-navigation">
					<header>Navigation</header>
					<div class="main-navigation navigation-off-canvas">
						<ul>
							<li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'index'),null,true);?>">Home</a></li>
							<li>
							 	<a href="#sub-level-1" class="has-child" data-toggle="collapse" aria-expanded="false" aria-controls="sub-level-1">Restaurant Management</a>
							 	<div class="collapse" id="sub-level-1">
									<ul>
										<?php $storage = new Zend_Auth_Storage_Session();
												$data = $storage->read();
												$resid = $data['RestId']?>
										<li><a href="<?php echo $this->url(array('module'=>'Restaurant','controller'=>'Restaurant','action'=>'firmregistration'),null,true);?>">Add Restaurant</a></li>
										<li><a href="<?php echo $this->url(array('module'=>'Restaurant','controller'=>'Restaurant','action'=>'firmedit','resid'=>$resid),null,true);?>">Edit Restaurant</a></li>
										<li><a href="<?php echo $this->url(array('module'=>'Restaurant','controller'=>'Restaurant','action'=>'menucategoryanditems','restaurantid'=>$resid),null,true);?>">Menu</a></li>
									</ul>
								</div>
							 </li>
							 <?php echo $this->loggedInAs();?>							
						</ul>

						<!--[if lte IE 9]>
						<script type="text/javascript" src="/js/ie-scripts.js"></script>
						<![endif]-->


						</div>
				</nav>
				<!--end Off Canvas Navigation-->
				<!--Page Content-->
				<div id="page-content">
					<?php echo $this->layout()->content ?>			
				</div>
			</div>
			<?php include('footer.phtml'); ?>
		</div>
	</div>
</body>
</html>
