<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>TecKnowledge</title>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/bootstrap.css">
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.css" type="text/css">
     <link rel="stylesheet" href="/css/style.css" type="text/css">
	<script type="text/javascript" src="/js/jquery.js"></script>
	 <script type="text/javascript" src="/js/jquery-1.7.js"></script>
	<script type="text/javascript" src="/bootstrap/js/bootstrap.min.js"></script>
		<script>
</script>
</head>
<style type="text/css">
.sidebar
{
	position: absolute;
	left:0px;
	width:20%;
	height:100%;
	background: #F6F6F7;
	overflow: auto;
	top:0%;
	border-right:2px solid black;
}
.main
{
	position: absolute;
	left:20%;
	width:80%;
	height:100%;
	background: white;
	top:0%;
}
.pageBtn
{
	background: black;
	color:white;
	width:20px;
	height: 20px;
	border-radius: 10px;
	margin:2px;
	border: none;
}
.dnone
{
	display: none;
}
</style>
</style>
<body>
<?php echo $this->layout()->content ?>	
</body>
</html>
