<script type="text/javascript" src="/theme/ui/jquery.ui.mouse.js"></script>
<script type="text/javascript" src="/theme/ui/jquery.ui.button.js"></script>
<script type="text/javascript" src="/theme/ui/jquery.ui.draggable.js"></script>
<script type="text/javascript" src="/theme/ui/jquery.ui.position.js"></script>
<script type="text/javascript" src="/theme/ui/jquery.ui.resizable.js"></script>
<script type="text/javascript" src="/theme/ui/jquery.ui.dialog.js"></script>

<script type="text/javascript">

$(document).ready(function(){
	$('.searchEmail').click(function(){
	 $(".error").hide();
	    var hasError = false;
	    var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;

	    var emailaddressVal = $("#email").val();
	        if(emailaddressVal == '') {
	        $("#email").after('<span class="error"><br/>'+"<? echo $this->translate->_("Please enter your email address."); ?>" +'</span>');
	        hasError = true;
	    	}

	    	else if(!emailReg.test(emailaddressVal)) {
	        $("#email").after('<span class="error"><br/>'+"<? echo $this->translate->_("Enter a valid Email Address."); ?>"+'</span>');
	        hasError = true;
	    	}

	    	if(hasError == true) {return false; }
	    	if(hasError == false){
    	      var result = ajaxCall();}
   });

	$('.cancelbtn').click(function(){
		$(".error").hide();
		var loginurl = "<?php echo $this->url(array('module'=>'User','controller'=>'Login','action'=>'signin'),null,true); ?>";
		window.location = loginurl;
	 });
	
	var firstname = "";
	var lastname = "";
	var userid = "";
	var emailObj = "";
	function ajaxCall(){
		var emailValid = false;
		emailObj = $("#email");
		var errorObj = $("#specialerror");
	 	var posturl = "<?php echo $this->url(array('module'=>'User','controller'=>'Client','action'=>'findemailidfordisrememberpassword'),null,true); ?>"
		 errorObj.text(" ");
		 if($.trim(emailObj.val()) != ""){
		 $.post(posturl, { email: $.trim(emailObj.val()) },
			   function(data){
			   if(data != "f"){
			  	emailValid = false;
			  		firstname = data['Firstname'];
					lastname = data['LastName'];
					userid = data['User_Id'];
					$('#emailaddress').text(emailObj.val());
					$('#username').text(data['Firstname'] +data['LastName']);
					$('#spanemail').text(emailObj.val());
					$('.userdetails').show();
					$('.emailenterform').hide();			
		   		}else if(data == 'f'){                                     
			   		$("#email").after('<span class="error"><br/>'+"<? echo $this->translate->_("Email address does not exist."); ?>"+'</span>');
			 		errorObj.css({'color':'#ED0E19'});
		   			emailValid = true;
		   		}
			},'json');	
		 }
	}
	$('.continuebtn').click(function(){
		var suburl = "<?php echo $this->url(array('module'=>'User','controller'=>'Client','action'=>'postcodefordisrememberpassword'),null,true); ?>";
			$.post(suburl, { email: $.trim(emailObj.val()),firstname : firstname,lastname : lastname, userid : userid },
			   function(data){
			      if(data != "f"){	
					$('.userdetails').hide();
					$('#userId').val(userid);
					$('.resetpassword').show();						
				   }
			   });
	});
	$('.notyou').click(function(){
		$("#email").val('');
		$('.userdetails').hide();
		$('.resetpassword').hide();
		$('.emailenterform').show();
	});
	var passwordmsg = "";
	var passwordmsg = "<?php echo $this->passwordmsg ?>";
	var UserId = "<?php echo $this->userid ?>";
	if(UserId != ''){
		$('#userId').val(UserId);
	}
	if(passwordmsg != ''){
		$('.resetpassword').show();
		$('.emailenterform').hide();
		$('.userdetails').hide();
	}else{
		$('.resetpassword').hide();
		$('.emailenterform').show();
	}
});

</script>

<style type="text/css">
.banner { /
	background: url(../images/topBg2.png) repeat-y -10px; /
	height: 80px;
	width: 1054px;
}
#loginwrapper {
  margin-top: 0px !important;
  margin-bottom:80px;
}
.block1 { 
	height: 50px;
}
.notyou{
	cursor:pointer;
}
.notyou:hover{ 
	text-decoration:underline;
}

.mtmainInner1{
	border:2px solid #ECECEC !important;;
	margin-bottom :20px; !important;
	margin-top: 20px; !important;
	background : none repeat scroll 0 0 #F7F7F7 !important;
}
.table3{
	text-align:left;
	margin:2px;
}

.table1 td {
	 font-size:11px;
}
.t1{
	font-size:18px;
	text-align:left;
}
.webpassword{
	background: #fff url(/images/icons/key.png) no-repeat 8px 8px;
	width: 272px;
    margin-bottom: 6px;
}
.webconfirm{
	background: #fff url(/images/icons/key.png) no-repeat 8px 8px;
	width: 272px;
    margin-bottom: 6px;
}
.username{
	background: #fff url(/images/icons/person.png) no-repeat 8px 8px;
	width: 272px;
    margin-bottom: 6px;
}

input, select, textarea {
	box-shadow: inset 1px 1px 5px #666;
	border-radius: 5px;
	height: 32px;
	border: 2px solid #F2F2F2;
	line-height: 32px;
	background: #fff;
	padding: 0 15px 0 35px;
	font-weight: bold;
	font-family: Century Gothic, Arial, Helvetica, sans-serif ;
	background: #eee;
	outline: none;
	transition: all 0.25s ease;
	-webkit-transition: all 0.25s ease;
	-moz-transition: all 0.25s ease;
	}
input[type="image"]{
	height:auto;
}
#nav{margin-top:0px !important;}
.mtmainInner1 {
  padding: 30px 20px;
  background: #ECF0F1;
  border: 0px solid rgba(147, 184, 189, 0.8) !important;
  -webkit-box-shadow: 5px;
  -moz-border-radius: 5px;
  border-radius: 5px;
}
input[type="radio"]{
	box-shadow: none;
	border-radius: 0px;
	border: 0px solid #F2F2F2;
	height: auto;
	}
</style>
<div class="mtmainInner1 userdetails" style="display:none; width: 800px; margin: 0 auto;margin-bottom:30px;">
	<div class="t1" style="border-bottom:1px solid #E0E0E0;"><?php echo $this->translate->_("Reset Your Password"); ?></div><br>
		<table class="table3" style="position:relative;left:15px;">	
			
			<tr>
				<td>
					<table>
						<tr>
							<th>
								<span class="a2"> <?php echo $this->translate->_("How would you like to reset your password"); ?></span>
							</th>
						</tr>
						<tr>
							<td>
								<input type="radio" checked="checked" name="emailbtn" />&nbsp;&nbsp;<img src="/images/icons/email.png" style="width:20px;"></img>&nbsp;&nbsp;<?php echo $this->translate->_("Email me the verification code to reset my password for"); ?><br><span id="spanemail" ></span>
							</td>
						</tr>
						<tr>
							<td>
								<input type="radio" disabled="disabled" />&nbsp;&nbsp;<img src="/images/icons/cell.png" style="width:20px;"></img>&nbsp;&nbsp;<?php echo $this->translate->_("Text me me the verification code to reset my password"); ?>
							</td>
						</tr>
					</table>
				</td>
				<td style="border-left:1px solid #E0E0E0">	 
				   <table class="table1" style="position:relative;left:35px; ">
						   <tr>
							    <td><span class="a2"><?php echo $this->translate->_("Name"); ?></span></td>
								<td>:</td>
								<td id="username" ></td>
							</tr>
							<tr>
								<td><span class="a2"><?php echo $this->translate->_("Email address"); ?> </span></td>
								<td>:</td>
								<td id="emailaddress"></td>
							</tr>
							<tr>
								<td>
									<div class="notyou a2" ><?php echo $this->translate->_("Not You?"); ?></div><br>
								</td>
							</tr>							
					  </table>
				  </td>	
			  </tr>	
		</table>
		
		<div class="btn fl" style="">
			<input type="image" src="/images/constcontinue.png" class="submitBtn continuebtn" style="top:0px; position:relative; left:265px;" />
		</div>	
		<div class="" style="" >
			<input type="image" src="/images/cancelbtn.png" class="submitBtn cancelbtn" style="top:0px; position:relative; left:40px; background: none repeat scroll 0 0 #F7F7F7;"/>
		</div>	
</div>

<div class="mtmainInner1 emailenterform" style="width: 550px; margin-left: 190px;">
		<div class="t1" style="border-bottom:1px solid #E0E0E0;"><?php echo $this->translate->_("Find Your Account"); ?></div><br></br>
		<div class="t3 a2"><?php echo $this->translate->_("Email or Username"); ?></div>
		<table class="table3" style="position:relative;left:105px;">		
			<tr>
				<td><img src="/images/icons/email.png" style="width:40px;"></img></td>
				<td>:</td>
				<td><input class="username" type="text" name="email" id="email" style="width:200px;"/>
					<span id="specialerror" class="error"></span></td>
				</td>
			</tr>
		</table>	
<!--		<div class="navTop" style="border:1px solid #E0E0E0;">-->
				<div class="btn f1" style="top:20px; position:relative; left:-50px;">
					<input type="image" src="/images/searchBTN1.png" class="submitBtn searchEmail" />
				</div>	
				<div class="btn f1" style="top:0px; position:relative; left:70px; top:-27px;">
					<input type="image" src="/images/cancelbtn.png" class="cancelbtn" style=" background: none repeat scroll 0 0 #F7F7F7;"/>
				</div>		
<!--		</div>-->
</div>
<div class="mtmainInner1 resetpassword" style="width: 550px; margin-left: 190px;">
<form method="post"	action="<?php echo $this->url(array('module'=>'User','controller'=>'Login','action'=>'resetpassword'),'default',true); ?>"	enctype="multipart/form-data">
	<div class="t1" style="border-bottom:1px solid #E0E0E0;"><?php echo $this->translate->_("Account Login"); ?></div>
		<br />
		<div class="t3" style="text-align:left;"><?php echo $this->translate->_("Check your email - we sent you an email with a confirmation code. Enter it below to continue to reset your password."); ?></div>
		<table class="table3">
			<tr>
				<td>
					<table class="table2">
						<tr>
							<td align="center">
								<?php if(isset($this->passwordmsg)){
									echo '<span style="color:red;font-size:12px;">'.$this->passwordmsg.'</span>';
								}		        	
								?>
							</td>
						</tr>	
						<tr>
							<td><?php echo $this->form->passphrase->setAttrib('placeholder',$this->translate->_('Verification Code*'))->setAttrib('class','username'); ?></td>
						</tr>
						<tr>
							<td><?php echo $this->form->password->setAttrib('placeholder',$this->translate->_('Password*'))->setAttrib('class','webpassword'); ?></td>
						</tr>
						<tr>
							<td><?php echo $this->form->password_confirm->setAttrib('placeholder',$this->translate->_('Confirm Password*'))->setAttrib('class','webconfirm'); ?></td>
						</tr>	
					</table>
				</td>
				<td>
					<div class="notyou" style="color:#F26722;" ><?php echo $this->translate->_("Didn't receive the code?"); ?></div><br>
					<div class="btn fl" style="position:relative; bottom:0px;">
						<input type="image" src="/images/constcontinue.png" class="submitBtn"  />
					</div>	
				</td>
			</tr>
		</table>
		<input type="hidden" id="userId" name="userid" />			
</form>
</div>
<!--</div>-->