<div class="sidebar">
	<button class="pageBtn" data-id="1">1</button>
	<button class="pageBtn" data-id="2">2</button>
	<button class="pageBtn" data-id="3">3</button>
</div>
<div class="main">
<div class="container">
<br/>
	<div class="row">
		<div class="col-md-11">
			<div class="panel panel-primary question" data-id="1">
			<div class="panel-heading">#1</div>
			1 Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</div>
			<div class="panel panel-primary question dnone" data-id="2">
			<div class="panel-heading">#2</div>
				2 Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</div>
		</div>
	</div>
</div>
</div>